### ISSUE TITLE
MMT engine cannot train or start on No-GPU environment

### ISSUE THREAD

**Issue by sallygaoxh** [modernmt/modernmt#462]
Hi,
I am using Ubuntu 16.04 and there is no GPU on my environment. So I skipped to use nvidia-docker but was using normal docker.

I followed the instructions on README, after entering the docker container, I tried:

`./mmt create en it examples/data/train --train-steps 6000`

But the training failed at step 4:
`INFO: (1 of 6) Corpora cleaning...                                     DONE (in 3s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 3s)
INFO: (3 of 6) Aligner training...                                     DONE (in 3s)
INFO: (4 of 6) Preparing data...                                      
ERROR Unexpected exception: None
Traceback (most recent call last):
  File "./mmt", line 612, in <module>
    main()
  File "./mmt", line 558, in main
    actions[command](args)
  File "./mmt", line 145, in main_create
    builder.build()
  File "/home/ubuntu/mmt/cli/mmt/engine.py", line 632, in build
    self._build(resume=False)
  File "/home/ubuntu/mmt/cli/mmt/engine.py", line 704, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/ubuntu/mmt/cli/mmt/engine.py", line 498, in __call__
    self._f(*args, **kwargs)
  File "/home/ubuntu/mmt/cli/mmt/engine.py", line 836, in _prepare_data
    log=log, bpe_symbols=self._bpe_symbols, fromModel=self._fromModel)
  File "/home/ubuntu/mmt/cli/mmt/engine.py", line 167, in prepare_data
    osutils.shell_exec(command, stdout=log, stderr=log, env=env)
  File "/home/ubuntu/mmt/clsli/libs/osutils.py", line 57, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.libs.osutils.ShellError: Command 't2t-datagen --t2t_usr_dir /home/ubuntu/mmt/build/lib/t2t --data_dir=/home/ubuntu/mmt/runtime/default/tmp/training/neural_train_data/data --tmp_dir=/home/ubuntu/mmt/runtime/default/tmp/training/neural_train_da
ta/tmp --problem=translate_mmt' failed with exit code -11`

This error msg is similar to https://github.com/modernmt/modernmt/issues/432, but cannot be solved since I am using Docker, all the settings should work. 

I doubted this error is caused by my no-gpu environment, so I tried to modify "/engines/default/engines.xconf" to the following script:
`<node xsi:schemaLocation="http://www.modernmt.eu/schema/config mmt-config-1.0.xsd"
      xmlns="http://www.modernmt.eu/schema/config"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <engine source-language="en" target-language="zh-CN" >
        <decoder enabled="true" gpus="none" threads="8" />
   </engine>
</node>`

Then I tried
`./mmt start`
Everything seems good till now:
`Starting MMT engine 'default'... OK
Loading models... OK
The MMT engine 'default' is ready.
You can try the API with:
        curl "http://localhost:8045/translate?q=world&source=en&target=it&context=computer" | python -mjson.tool`

But when I tried to check the status of my engine, I have:
`root@9c62eb0d4611:/home/ubuntu/mmt# ./mmt status
[Engine: "default"]
    REST API:   stopped
    Cluster:    stopped
    Datastream: stopped
    Database:   stopped`
which is similar to https://github.com/modernmt/modernmt/issues/457 but also not the same situation. I don't think my engine is trained since it failed when I created it. But I do not know how to train it again.

Can you please help me out? Am I doing correctly without GPU? How should I train my engine after modifying the engines.xconf.

**Comment by sallygaoxh** [comment]
And here is my log file: /runtime/default/log/node.log

>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-18 21:41:21,774 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2019-04-18 21:41:21,803 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2019-04-18 21:41:21,804 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
        at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:91)
        at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
2019-04-18 21:49:30,512 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2019-04-18 21:49:31,659 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.817s
2019-04-18 21:49:31,824 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2019-04-18 21:49:31,854 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loading FastAlign models
2019-04-18 21:49:31,874 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loaded 1 FastAlign models in 0s
2019-04-18 21:49:32,243 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process on CPU is starting
2019-04-18 21:49:32,243 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-2] Native decoder process on CPU is starting
2019-04-18 21:49:32,244 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-3] Native decoder process on CPU is starting
2019-04-18 21:49:32,244 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-5] Native decoder process on CPU is starting
2019-04-18 21:49:32,245 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-6] Native decoder process on CPU is starting
2019-04-18 21:49:32,245 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-4] Native decoder process on CPU is starting
2019-04-18 21:49:32,245 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-7] Native decoder process on CPU is starting
2019-04-18 21:49:32,245 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-8] Native decoder process on CPU is starting
2019-04-18 21:49:32,589 ERROR eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process on CPU failed to start
java.io.IOException: Failed to start neural decoder, received: null
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl.init(PythonDecoderImpl.java:123)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:94)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.startOnCPU(PythonDecoderImpl.java:56)
        at eu.modernmt.decoder.neural.execution.impl.Handler.restart(Handler.java:53)
        at eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:196)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-18 21:49:32,625 ERROR eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-2] Native decoder process on CPU failed to start
java.io.IOException: Failed to start neural decoder, received: null
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl.init(PythonDecoderImpl.java:123)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:94)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.startOnCPU(PythonDecoderImpl.java:56)
        at eu.modernmt.decoder.neural.execution.impl.Handler.restart(Handler.java:53)
        at eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:196)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-18 21:49:32,636 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2019-04-18 21:49:32,664 ERROR eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-5] Native decoder process on CPU failed to start
java.io.IOException: Failed to start neural decoder, received: null
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl.init(PythonDecoderImpl.java:123)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:94)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.startOnCPU(PythonDecoderImpl.java:56)
        at eu.modernmt.decoder.neural.execution.impl.Handler.restart(Handler.java:53)
        at eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:196)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-18 21:49:32,673 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2019-04-18 21:49:32,673 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
        at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:91)
        at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)

**Comment by nicolabertoldi** [comment]
@sallygaoxh 
At the moment, the training of an engine is possible on GPU only.

So, the engine you got after the failure is definitely incomplete and not usable.

**Comment by cettolo** [comment]
Hi sallygaoxh

setting the env variable:
CUDA_VISIBLE_DEVICES=-1
mmt processes run on cpu only. Try:

> CUDA_VISIBLE_DEVICES=-1  ./mmt create...
and/or
> CUDA_VISIBLE_DEVICES=-1 ./mmt start...

Typically I use that setting on GPU equipped machines when GPU is heavily used by other processes. But some time ago (if I remember well) I successfully run the same on a machine without GPU at all. Of course the processing time (especially for training) increases a lot.

**Comment by Hasan0ff** [comment]
@cettolo Mauro, do you have approximate numbers regarding the training time for non-gpu machine?

**Comment by cettolo** [comment]
@Hasan0ff Actually, I didn't run real trainings on CPU due to their cost. On the default MMT example, specifying the "transformer_tiny" model (~3M parameters to train), on my 8 core CPU, equipped with a GeForce GTX TITAN GPU, in training.log I see that performing 100 updates takes:
- CPU: approx 270 seconds
- GPU: approx 10 seconds
Mauro

**Comment by Hasan0ff** [comment]
@cettolo , Mauro thank you very much for the reply. I'm going to buy a machine to run MMT. I'll use the results that you show (TITAN GPU has 2688 cuda cores) to compare with the results i get after the tests (im planning to get gt1030 or 1050 with less than 1000 cuda cores). Again, thank you very much for the response.

**Comment by jgrivolla** [comment]
It's not working for me, even with the `CUDA_VISIBLE_DEVICES=-1` parameter:
```
ubuntu@131f3e2c1103:/mmt$ CUDA_VISIBLE_DEVICES=-1 ./mmt start
Starting MMT engine 'default'... OK
Loading models... OK

The MMT engine 'default' is ready.

You can try the API with:
	curl "http://localhost:8045/translate?q=world&source=en&target=it&context=computer" | python -mjson.tool

ubuntu@131f3e2c1103:/mmt$ ./mmt status
[Engine: "default"]
    REST API:   stopped
    Cluster:    stopped
    Datastream: stopped
    Database:   stopped
```
The model is trained correctly and can be run on a machine with GPU, but it will not run on only CPU.

**Comment by cettolo** [comment]
Which engine version are you using, v3.3 or v4? I ask because it worked for me with 3.* but I never tried with the latest release.

**Comment by jgrivolla** [comment]
@cettolo : my problems described above are with v3.3. I haven't tried using v4 yet. The strange thing is that it claims to start up correctly, but isn't running afterwards.

**Comment by cettolo** [comment]
give a look at the log file runtime/<enginename>/logs/node.log, likely you can find there the reason for which the starting fails

**Comment by cettolo** [comment]
runtime/_enginename_/logs/node.log

**Comment by jgrivolla** [comment]
Thanks @cettolo, it does show an exception in the logs, but I'm not quite sure how to interpret it:
```
2019-05-17 17:20:25,497 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2019-05-17 17:20:26,735 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.939s
2019-05-17 17:20:26,927 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2019-05-17 17:20:26,978 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loading FastAlign models
2019-05-17 17:20:27,627 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loaded 1 FastAlign models in 0s
2019-05-17 17:20:27,916 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process on CPU is starting
2019-05-17 17:20:27,918 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-2] Native decoder process on CPU is starting
2019-05-17 17:20:28,124 ERROR eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-2] Native decoder process on CPU failed to start
java.io.IOException: Failed to start neural decoder, received: null
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl.init(PythonDecoderImpl.java:123)
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:94)
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.startOnCPU(PythonDecoderImpl.java:56)
	at eu.modernmt.decoder.neural.execution.impl.Handler.restart(Handler.java:53)
	at eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-05-17 17:20:28,128 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2019-05-17 17:20:28,140 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2019-05-17 17:20:28,141 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
	at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:91)
	at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
```
It does look similar to #457 so I'm working through that one to see if the comments are applicable to my situation.

**Comment by nicolabertoldi** [comment]
@jgrivolla 

could you please post the content of `engines/enginename/engine.xconf`?

**Comment by jgrivolla** [comment]
@nicolabertoldi : 
```
ubuntu@131f3e2c1103:/mmt/engines/default$ cat engine.xconf 
<node xsi:schemaLocation="http://www.modernmt.eu/schema/config mmt-config-1.0.xsd"
      xmlns="http://www.modernmt.eu/schema/config"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <engine source-language="ar" target-language="en" />
```

**Comment by nicolabertoldi** [comment]
@jgrivolla 

this command 
```CUDA_VISIBLE_DEVICES=-1 ./mmt start```
works as expected on a chine with at least one GPU on board; i.e. it does not decode with the GPU, but only with the CPU

Is this your case, or rather do you have a machine without GPU?

**Comment by jgrivolla** [comment]
@nicolabertoldi I'm trying to run it on a machine without a (sufficiently CUDA-compatible) GPU at all.

**Comment by nicolabertoldi** [comment]
@jgrivolla 

last question before debugging:
which version of Linux?

are you sure to be interested in running the system on CPU?
As you know, decoding time is definitely larger.

**Comment by jgrivolla** [comment]
Docker 19.03 on Ubuntu 18.10
Unfortunately there may be many situations where we can't deploy on machines with GPU (e.g. our virtual servers here at the University don't have them), so running on CPU can be quite important for us.

**Comment by nicolabertoldi** [comment]
@jgrivolla 

I just succeeded to use an engine on a machine without GPU having Ubuntu 18.
The model was trained on a machine with GPU on board


The issue was related to the usage of the Python package `tensorflow-gpu`.
Instead, if the package `tensorflow` is installed everything works fine.

Unfortunately,  docker image for ModernMT was prepared for running on a GPU-based machine, and so includes the "wrong" package `tensorflow-gpu`.

Hence, in order to have a ModernMT instance working on a CPU-only machine, you have to install it from the source, following these instructions 
https://github.com/modernmt/modernmt/blob/v3.3/INSTALL.md#installing-third-party-libraries
and replacing this instruction 
```pip install tensorflow-gpu==1.8.0```
with this
```pip install tensorflow==1.8.0```


Hope this solves the issue.

If so, please close the ticket.

**Comment by jgrivolla** [comment]
Thank you so much @nicolabertoldi (and @cettolo ) for your help.

I just tried it the lazy way by simply doing `pip install tensorflow==1.8.0` on top of the existing Docker image and it appears to work perfectly. This means that I can very easily create a derived Docker image to use on CPU. I haven't tested yet if that same image also still works with GPU, in which case I could just use the same image for both cases (or this could be added to the standard image).

**Comment by davidecaroselli** [comment]
Thanks all for the contributions! However please keep in mind that running ModernMT **without a GPU** is still not its intended use case, so there could be problems here and there during installation and runtime, even for ModernMT v4.0.

Anyways, thanks again for all your support and please feel free to re-open this issue for further discussions!
