### ISSUE TITLE
ERROR Unexpected exception: Command 'fairseq-preprocess

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#474]
`./mmt create ja nl data/japdut -e japdut --tensorboard-port 8066

=========== TRAINING STARTED ===========

ENGINE:   japdut
LANGUAGE: ja > nl

(1/4) Cleaning corpora
    (1/6) Cleaning corpora...                                    DONE in 3s
    (2/6) De-duplicate corpora...                                DONE in 0s
    (3/6) Preprocess corpora...                                  DONE in 2s
    (4/6) Creating aligner filter...                             DONE in 4s
    (5/6) Scoring corpora...                                     DONE in 0s
    (6/6) Apply aligner-based filter...                          DONE in 0s
(1/4) Cleaning corpora DONE in 11s
(2/4) Creating engine
(2/4) Creating engine DONE in 0s
(3/4) Generating binary archives
    (1/4) Tokenize corpora...                                    DONE in 3s
    (2/4) Training BPE model...                                  DONE in 47s
    (3/4) Encoding training corpora...                           DONE in 0s
    (4/4) Generating binary data...                              
ERROR Unexpected exception: Command 'fairseq-preprocess --source-lang sl --target-lang tl --user-dir /home/loek/mmt9/modernmt/build/mmt-4.0.jar/mmt --task mmt_translation --trainpref /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/encoded_corpora/train --validpref /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/encoded_corpora/dev --destdir /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/data_generated --workers 8 --srcdict /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/data_generated/model.vcb --joined-dictionary' failed with exit code 1
`

**Comment by LoekvanKooten** [comment]
`2019-05-07 11:17:46,014 [INFO] - Training started: engine=japdut, lang_pair=ja__nl
2019-05-07 11:17:46,043 [INFO] - Training step "clean" started
2019-05-07 11:17:46,045 [INFO] - Training step "clean" started
2019-05-07 11:17:46,047 [DEBUG] - java -DentityExpansionLimit=0 -DtotalEntitySizeLimit=0 -Djdk.xml.totalEntitySizeLimit=0 -Xmx14398m -cp /home/loek/mmt9/modernmt/build/mmt-4.0.jar -Dmmt.home=/home/loek/mmt9/modernmt -Djava.library.path=/home/loek/mmt9/modernmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s ja -t nl --input data/japdut --output /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/clean_corpora --output-format parallel
2019-05-07 11:17:49,586 [INFO] - Training step "clean" completed in 3s
2019-05-07 11:17:49,586 [INFO] - Training step "dedup" started
2019-05-07 11:17:49,586 [DEBUG] - java -cp /home/loek/mmt9/modernmt/build/mmt-4.0.jar -Dmmt.home=/home/loek/mmt9/modernmt -Djava.library.path=/home/loek/mmt9/modernmt/build/lib eu.modernmt.cli.DeduplicationMain -s ja -t nl --input /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/clean_corpora --output /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/dedup_corpora
2019-05-07 11:17:50,120 [INFO] - Training step "dedup" completed in 0s
2019-05-07 11:17:50,121 [INFO] - Training step "preprocess" started
2019-05-07 11:17:50,121 [DEBUG] - java -cp /home/loek/mmt9/modernmt/build/mmt-4.0.jar -Dmmt.home=/home/loek/mmt9/modernmt -Djava.library.path=/home/loek/mmt9/modernmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s ja -t nl --output /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/preprocessed_corpora --input /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/dedup_corpora
2019-05-07 11:17:52,270 [INFO] - Training step "preprocess" completed in 2s
2019-05-07 11:17:52,271 [INFO] - Training step "make_filter" started
2019-05-07 11:17:52,271 [DEBUG] - /home/loek/mmt9/modernmt/build/bin/fa_build -s ja -t nl -i /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/preprocessed_corpora -m /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/aligner/ja__nl.fam -I 4 --case-insensitive --no-favor-diagonal
Build started with options: {alpha=0.01, buffer_size=10000, case_sensitive=false, favor_diagonal=false, initial_diagonal_tension=4, iterations=4, max_length=80, optimize_tension=true, prob_align_null=0.08, pruning=1e-20, threads=8, use_null=true, variational_bayes=true, vocabulary_threshold=0.9999}
Creating vocabulary... DONE in 0.317702s
== Forward model training ==
Initial setup... DONE in 0.423274s
Iteration 1:
	Computing alignments... DONE in 0.20158s
	Normalizing translation table... DONE in 0.151986s
Iteration 2:
	Computing alignments... DONE in 0.201587s
	Normalizing translation table... DONE in 0.152153s
Iteration 3:
	Computing alignments... DONE in 0.201516s
	Normalizing translation table... DONE in 0.149617s
Iteration 4:
	Computing alignments... DONE in 0.201697s
	Normalizing translation table... DONE in 0.149773s
Pruning model... DONE in 0.0337698s

Training DONE in 1.86723s

== Backward model training ==
Initial setup... DONE in 0.40193s
Iteration 1:
	Computing alignments... DONE in 0.193377s
	Normalizing translation table... DONE in 0.154133s
Iteration 2:
	Computing alignments... DONE in 0.193974s
	Normalizing translation table... DONE in 0.153622s
Iteration 3:
	Computing alignments... DONE in 0.197676s
	Normalizing translation table... DONE in 0.15429s
Iteration 4:
	Computing alignments... DONE in 0.19491s
	Normalizing translation table... DONE in 0.153049s
Pruning model... DONE in 0.0343232s

Training DONE in 1.83343s

Writing model...DONE in 0.058434s
2019-05-07 11:17:56,483 [INFO] - Training step "make_filter" completed in 4s
2019-05-07 11:17:56,484 [INFO] - Training step "score" started
2019-05-07 11:17:56,484 [DEBUG] - /home/loek/mmt9/modernmt/build/bin/fa_score -s ja -t nl -m /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/aligner/ja__nl.fam -i /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/preprocessed_corpora -o /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_cleaning/preprocessed_corpora
2019-05-07 11:17:57,341 [INFO] - Training step "score" completed in 0s
2019-05-07 11:17:57,342 [INFO] - Training step "apply_filter" started
2019-05-07 11:17:57,342 [INFO] - Applying aligner filter with: good_avg = -4.531120, good_std_dev = 1.717380, bad_avg = -12.474400, bad_std_dev = 4.110020
2019-05-07 11:17:57,475 [INFO] - Training step "apply_filter" completed in 0s
2019-05-07 11:17:57,478 [INFO] - Training step "clean" completed in 11s
2019-05-07 11:17:57,478 [INFO] - Training step "mkengine" started
2019-05-07 11:17:57,478 [INFO] - Training step "mkengine" completed in 0s
2019-05-07 11:17:57,478 [INFO] - Training step "datagen" started
2019-05-07 11:17:57,478 [INFO] - Training step "tokenize" started
2019-05-07 11:17:57,478 [DEBUG] - java -cp /home/loek/mmt9/modernmt/build/mmt-4.0.jar -Dmmt.home=/home/loek/mmt9/modernmt -Djava.library.path=/home/loek/mmt9/modernmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s ja -t nl --output /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/tokenized_corpora/ja__nl/train --input /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/corpora_clean --size 3000 --dev /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/tokenized_corpora/ja__nl/_dev --test /home/loek/mmt9/modernmt/engines/japdut/test_data/ja__nl
2019-05-07 11:17:59,594 [DEBUG] - java -cp /home/loek/mmt9/modernmt/build/mmt-4.0.jar -Dmmt.home=/home/loek/mmt9/modernmt -Djava.library.path=/home/loek/mmt9/modernmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s ja -t nl --output /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/tokenized_corpora/ja__nl/dev --input /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/tokenized_corpora/ja__nl/_dev
2019-05-07 11:18:00,744 [INFO] - Training step "tokenize" completed in 3s
2019-05-07 11:18:00,745 [INFO] - Training step "bpe_create" started
2019-05-07 11:18:00,745 [INFO] - Collecting counts BEGIN
2019-05-07 11:18:00,856 [INFO] - Collecting counts END
2019-05-07 11:18:00,889 [INFO] - Vocabulary max_size attempt with candidates = [16000, 32000]
2019-05-07 11:18:00,927 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:00,935 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:02,133 [INFO] - iteration 1 END, vocab_size = 2914
2019-05-07 11:18:02,133 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:02,141 [INFO] - iteration 1 END, vocab_size = 2903
2019-05-07 11:18:02,141 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:03,279 [INFO] - iteration 2 END, vocab_size = 2912
2019-05-07 11:18:03,338 [INFO] - iteration 2 END, vocab_size = 2902
2019-05-07 11:18:03,396 [INFO] - Generating vocab file: min = 1, max = 16000
2019-05-07 11:18:03,396 [INFO] - Trying min_count 8000
2019-05-07 11:18:03,409 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:04,574 [INFO] - iteration 1 END, vocab_size = 2962
2019-05-07 11:18:04,574 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:05,573 [INFO] - iteration 2 END, vocab_size = 2950
2019-05-07 11:18:05,573 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:06,595 [INFO] - iteration 3 END, vocab_size = 2953
2019-05-07 11:18:06,595 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:07,575 [INFO] - iteration 4 END, vocab_size = 2953
2019-05-07 11:18:07,581 [INFO] - Trying min_count 4000
2019-05-07 11:18:07,590 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:08,757 [INFO] - iteration 1 END, vocab_size = 3042
2019-05-07 11:18:08,757 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:09,668 [INFO] - iteration 2 END, vocab_size = 3001
2019-05-07 11:18:09,668 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:10,635 [INFO] - iteration 3 END, vocab_size = 3004
2019-05-07 11:18:10,635 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:11,560 [INFO] - iteration 4 END, vocab_size = 3003
2019-05-07 11:18:11,566 [INFO] - Trying min_count 2000
2019-05-07 11:18:11,576 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:12,745 [INFO] - iteration 1 END, vocab_size = 3181
2019-05-07 11:18:12,745 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:13,559 [INFO] - iteration 2 END, vocab_size = 3092
2019-05-07 11:18:13,559 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:14,407 [INFO] - iteration 3 END, vocab_size = 3099
2019-05-07 11:18:14,407 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:15,263 [INFO] - iteration 4 END, vocab_size = 3097
2019-05-07 11:18:15,268 [INFO] - Trying min_count 1000
2019-05-07 11:18:15,278 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:16,453 [INFO] - iteration 1 END, vocab_size = 3435
2019-05-07 11:18:16,453 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:17,236 [INFO] - iteration 2 END, vocab_size = 3239
2019-05-07 11:18:17,236 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:18,058 [INFO] - iteration 3 END, vocab_size = 3260
2019-05-07 11:18:18,058 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:18,870 [INFO] - iteration 4 END, vocab_size = 3261
2019-05-07 11:18:18,875 [INFO] - Trying min_count 500
2019-05-07 11:18:18,885 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:20,058 [INFO] - iteration 1 END, vocab_size = 3970
2019-05-07 11:18:20,058 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:20,773 [INFO] - iteration 2 END, vocab_size = 3526
2019-05-07 11:18:20,773 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:21,542 [INFO] - iteration 3 END, vocab_size = 3562
2019-05-07 11:18:21,542 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:22,306 [INFO] - iteration 4 END, vocab_size = 3560
2019-05-07 11:18:22,311 [INFO] - Trying min_count 250
2019-05-07 11:18:22,321 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:23,534 [INFO] - iteration 1 END, vocab_size = 4967
2019-05-07 11:18:23,535 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:24,206 [INFO] - iteration 2 END, vocab_size = 4039
2019-05-07 11:18:24,206 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:24,929 [INFO] - iteration 3 END, vocab_size = 4081
2019-05-07 11:18:24,929 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:25,613 [INFO] - iteration 4 END, vocab_size = 4090
2019-05-07 11:18:25,617 [INFO] - Trying min_count 125
2019-05-07 11:18:25,627 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:26,790 [INFO] - iteration 1 END, vocab_size = 6869
2019-05-07 11:18:26,790 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:27,388 [INFO] - iteration 2 END, vocab_size = 4906
2019-05-07 11:18:27,388 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:28,035 [INFO] - iteration 3 END, vocab_size = 5031
2019-05-07 11:18:28,035 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:28,663 [INFO] - iteration 4 END, vocab_size = 4987
2019-05-07 11:18:28,667 [INFO] - Trying min_count 62
2019-05-07 11:18:28,676 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:29,851 [INFO] - iteration 1 END, vocab_size = 10225
2019-05-07 11:18:29,852 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:30,407 [INFO] - iteration 2 END, vocab_size = 6440
2019-05-07 11:18:30,407 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:31,038 [INFO] - iteration 3 END, vocab_size = 6608
2019-05-07 11:18:31,038 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:31,642 [INFO] - iteration 4 END, vocab_size = 6577
2019-05-07 11:18:31,646 [INFO] - Trying min_count 31
2019-05-07 11:18:31,655 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:32,877 [INFO] - iteration 1 END, vocab_size = 15719
2019-05-07 11:18:32,877 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:33,418 [INFO] - iteration 2 END, vocab_size = 8875
2019-05-07 11:18:33,418 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:33,995 [INFO] - iteration 3 END, vocab_size = 9170
2019-05-07 11:18:33,995 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:34,552 [INFO] - iteration 4 END, vocab_size = 9132
2019-05-07 11:18:34,556 [INFO] - Trying min_count 15
2019-05-07 11:18:34,566 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:35,800 [INFO] - iteration 1 END, vocab_size = 25321
2019-05-07 11:18:35,800 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:36,317 [INFO] - iteration 2 END, vocab_size = 12975
2019-05-07 11:18:36,317 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:36,832 [INFO] - iteration 3 END, vocab_size = 13387
2019-05-07 11:18:36,832 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:37,338 [INFO] - iteration 4 END, vocab_size = 13280
2019-05-07 11:18:37,343 [INFO] - Trying min_count 7
2019-05-07 11:18:37,352 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:38,611 [INFO] - iteration 1 END, vocab_size = 42008
2019-05-07 11:18:38,611 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:39,086 [INFO] - iteration 2 END, vocab_size = 19925
2019-05-07 11:18:39,086 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:39,579 [INFO] - iteration 3 END, vocab_size = 20492
2019-05-07 11:18:39,579 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:40,067 [INFO] - iteration 4 END, vocab_size = 20371
2019-05-07 11:18:40,072 [INFO] - Trying min_count 3
2019-05-07 11:18:40,082 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:41,491 [INFO] - iteration 1 END, vocab_size = 74200
2019-05-07 11:18:41,491 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:41,968 [INFO] - iteration 2 END, vocab_size = 32626
2019-05-07 11:18:41,968 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:42,451 [INFO] - iteration 3 END, vocab_size = 33444
2019-05-07 11:18:42,451 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:42,930 [INFO] - iteration 4 END, vocab_size = 33261
2019-05-07 11:18:42,935 [INFO] - Trying min_count 5
2019-05-07 11:18:42,945 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:44,247 [INFO] - iteration 1 END, vocab_size = 52582
2019-05-07 11:18:44,247 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:44,721 [INFO] - iteration 2 END, vocab_size = 24148
2019-05-07 11:18:44,721 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:45,219 [INFO] - iteration 3 END, vocab_size = 24839
2019-05-07 11:18:45,219 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:45,708 [INFO] - iteration 4 END, vocab_size = 24696
2019-05-07 11:18:45,713 [INFO] - Trying min_count 4
2019-05-07 11:18:45,723 [INFO] - iteration 1 BEGIN
2019-05-07 11:18:47,088 [INFO] - iteration 1 END, vocab_size = 61388
2019-05-07 11:18:47,088 [INFO] - iteration 2 BEGIN
2019-05-07 11:18:47,565 [INFO] - iteration 2 END, vocab_size = 27612
2019-05-07 11:18:47,566 [INFO] - iteration 3 BEGIN
2019-05-07 11:18:48,055 [INFO] - iteration 3 END, vocab_size = 28343
2019-05-07 11:18:48,055 [INFO] - iteration 4 BEGIN
2019-05-07 11:18:48,535 [INFO] - iteration 4 END, vocab_size = 28203
2019-05-07 11:18:48,570 [INFO] - Training step "bpe_create" completed in 47s
2019-05-07 11:18:48,571 [INFO] - Training step "bpe_encode" started
2019-05-07 11:18:49,242 [INFO] - Training step "bpe_encode" completed in 0s
2019-05-07 11:18:49,242 [INFO] - Training step "datagen" started
2019-05-07 11:18:49,243 [DEBUG] - fairseq-preprocess --source-lang sl --target-lang tl --user-dir /home/loek/mmt9/modernmt/build/mmt-4.0.jar/mmt --task mmt_translation --trainpref /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/encoded_corpora/train --validpref /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/_temp_datagen/encoded_corpora/dev --destdir /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/data_generated --workers 8 --srcdict /home/loek/mmt9/modernmt/runtime/japdut/tmp/training/data_generated/model.vcb --joined-dictionary
Traceback (most recent call last):
  File "/home/loek/.local/bin/fairseq-preprocess", line 7, in <module>
    from fairseq_cli.preprocess import cli_main
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq_cli/preprocess.py", line 15, in <module>
    from fairseq import options, tasks
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/__init__.py", line 12, in <module>
    import fairseq.models
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/models/__init__.py", line 15, in <module>
    from .fairseq_model import (
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/models/fairseq_model.py", line 14, in <module>
    from fairseq.data import Dictionary
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/data/__init__.py", line 8, in <module>
    from .dictionary import Dictionary, TruncatedDictionary
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/data/dictionary.py", line 16, in <module>
    from fairseq.data import data_utils
  File "/home/loek/.local/lib/python3.5/site-packages/fairseq/data/data_utils.py", line 159
    assert sample_len <= max_tokens, f"sentence at index {idx} exceeds max_tokens limit!"
                                                                                        ^
SyntaxError: invalid syntax`

**Comment by davidecaroselli** [comment]
> /home/loek/.local/lib/python3.5

@LoekvanKooten you're still using python 3.5
Anyways, I'm adding a more clear alert at the beginning of `mmt` command in order to be more clear on the minimum python requirements

**Comment by LoekvanKooten** [comment]
@davidecaroselli 3.7 is the default Python according to update-alternatives. Why does MMT pick 3.5 after all? How do I force it to pick 3.7?

**Comment by davidecaroselli** [comment]
A well-configured Unix platform should have two python commands: `python` and `python3`. This is done in order to prevent messing with the legacy "python" scripts written for Python 2 (some of them are even os level!). Following this standard, ModernMT (just like all python3 scripts) explicitly uses `python3` binary.

So a well-configured platform should behave like this:
```bash
$ python --version
Python 2.7.12
$ python2 --version
Python 2.7.12
$ python3 --version
Python 3.6.7
```

**Comment by LoekvanKooten** [comment]
python3 --version
gives me 
Python 3.7.3

@davidecaroselli

**Comment by LoekvanKooten** [comment]
(python and python2 give 2.7.15)

**Comment by davidecaroselli** [comment]
Let's see if there is some problem on how fairseq has been installed.

First locate the binary `fairseq-preprocess`:
```bash
$ which fairseq-preprocess 
/usr/local/bin/fairseq-preprocess
```

Not look at the source code:
```bash
$ cat /usr/local/bin/fairseq-preprocess
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'fairseq','console_scripts','fairseq-preprocess'
__requires__ = 'fairseq'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')()
    )
```

Look at the very first line `#!/usr/bin/python3` what reports your `fairseq-preprocess`?

**Comment by LoekvanKooten** [comment]
`loek@DORAEMON:~/mmt8$  which fairseq-preprocess 
/home/loek/.local/bin/fairseq-preprocess
loek@DORAEMON:~/mmt8$ cat /home/loek/.local/bin/fairseq-preprocess
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from fairseq_cli.preprocess import cli_main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli_main())
`

@davidecaroselli

**Comment by davidecaroselli** [comment]
which version of fairseq are you using? This does not look like v 0.6.2

**Comment by LoekvanKooten** [comment]
How do I check this?

@davidecaroselli

**Comment by davidecaroselli** [comment]
Actually this should depend on which pip version installed fairseq.

Nevermind, @LoekvanKooten you **need** to cleanup your environment, you have some serious configuration problems. I suggest to totally remove packages and even python3.7 installation and then re-apply the installation step by step double-checking that you're using the expected configuration.

More importart, you be 100% sure that your `pip3 --version` Python version match the python version of `python3 --version`.

Even more important, if this is possible for you, change your operating system. With Ubuntu 18.04 the installation will run smoothly (for example python 3.6 is the default python3 version on Ubuntu 18.04).  Or if you don't want to waste time, you can use Docker images that will run no matter what.

**Comment by davidecaroselli** [comment]
I'm closing this issue so that we can continue on this:
https://github.com/modernmt/modernmt/issues/475
