### ISSUE TITLE
ModernMT v3 - "Something is wrong with the numpy installation" error

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#479]
@davidecaroselli @nicolabertoldi I´m afraid I need your help urgently. My system is down and I need to get it up and running ASAP again. This is on Ubuntu 16.04 with MMT 3.3.1

On a brand-new system, after following the installation instructions to the letter (I tried 3 times), this happens:

`./mmt create ja nl data/japdut -e japdut

=========== TRAINING STARTED ===========

ENGINE:  japdut
CORPORA: 16 corpora
LANGS:   ja > nl

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 3s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 3s)
INFO: (3 of 6) Aligner training...                                     DONE (in 5s)
INFO: (4 of 6) Preparing data...                                      
ERROR Unexpected exception: None

Traceback (most recent call last):
  File "./mmt", line 612, in <module>
    main()
  File "./mmt", line 558, in main
    actions[command](args)
  File "./mmt", line 145, in main_create
    builder.build()
  File "/home/loek/mmt/cli/mmt/engine.py", line 632, in build
    self._build(resume=False)
  File "/home/loek/mmt/cli/mmt/engine.py", line 704, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/loek/mmt/cli/mmt/engine.py", line 498, in __call__
    self._f(*args, **kwargs)
  File "/home/loek/mmt/cli/mmt/engine.py", line 836, in _prepare_data
    log=log, bpe_symbols=self._bpe_symbols, fromModel=self._fromModel)
  File "/home/loek/mmt/cli/mmt/engine.py", line 167, in prepare_data
    osutils.shell_exec(command, stdout=log, stderr=log, env=env)
  File "/home/loek/mmt/cli/libs/osutils.py", line 57, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.libs.osutils.ShellError: Command 't2t-datagen --t2t_usr_dir /home/loek/mmt/build/lib/t2t --data_dir=/home/loek/mmt/runtime/japdut/tmp/training/neural_train_data/data --tmp_dir=/home/loek/mmt/runtime/japdut/tmp/training/neural_train_data/tmp --problem=translate_mmt' failed with exit code 1
`

**Comment by LoekvanKooten** [comment]
t2t-datagen then gives:

`Traceback (most recent call last):
  File "/home/loek/.local/bin/t2t-datagen", line 18, in <module>
    from tensor2tensor.bin import t2t_datagen
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_datagen.py", line 39, in <module>
    import numpy as np
  File "/home/loek/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/loek/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/loek/.local/lib/python2.7/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.
`
pip uninstall numpyTraceback (most recent call last):
  File "/home/loek/.local/bin/t2t-datagen", line 18, in <module>
    from tensor2tensor.bin import t2t_datagen
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_datagen.py", line 39, in <module>
    import numpy as np
  File "/home/loek/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/loek/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/loek/.local/lib/python2.7/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

`pip uninstall numpy
pip uninstall numpy`
removes all numpy´s

`pip install numpy==1.14.5`
reinstalls numpy

t2t-datagen then gives:

`Traceback (most recent call last):
  File "/home/loek/.local/bin/t2t-datagen", line 18, in <module>
    from tensor2tensor.bin import t2t_datagen
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_datagen.py", line 41, in <module>
    from tensor2tensor import problems as problems_lib  # pylint: disable=unused-import
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/problems.py", line 26, in <module>
    from tensor2tensor.data_generators import all_problems  # pylint: disable=unused-import
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/all_problems.py", line 94, in <module>
    importlib.import_module(_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/algorithmic.py", line 26, in <module>
    from tensor2tensor.data_generators import generator_utils as utils
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/generator_utils.py", line 36, in <module>
    from tensor2tensor.data_generators import text_encoder
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 37, in <module>
    from tensor2tensor.data_generators import tokenizer
  File "/home/loek/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/tokenizer.py", line 54, in <module>
    import tensorflow as tf
  File "/home/loek/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/loek/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/loek/.local/lib/python2.7/site-packages/tensorflow/python/framework/framework_lib.py", line 104, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/loek/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 32, in <module>
    from tensorflow.python.framework import function
  File "/home/loek/.local/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/home/loek/.local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 35, in <module>
    from tensorflow.python.ops import variables
  File "/home/loek/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 40, in <module>
    class Variable(checkpointable.CheckpointableBase):
AttributeError: 'module' object has no attribute 'CheckpointableBase'`

This seems to be related to a wrong file (an actual bug) in CUDA/CuDN, but I´m stuck.

**Comment by LoekvanKooten** [comment]
It *seems* to work right now after uninstalling and re-installing numpy a few times. It´s related to numpy and/or this part of the instructions:

`pip install -U requests
pip install numpy==1.14.5
pip install tensorflow-gpu==1.8.0
pip install tensor2tensor==1.6.3

pip install --upgrade oauth2client`

Maybe even to pip (upgrading breaks it, but pinning it to 9.0.something may have some influence).

**Comment by LoekvanKooten** [comment]
I'd be very much obliged if you tried this on a clean Ubuntu 16.04 system to see what exactly goes wrong where. I only spent 18 hours figuring this out and I"m still not sure. As said, it *seems* to be working now, but I'm not assured at all. I dare not even turn the system off now.

**Comment by davidecaroselli** [comment]
I'll give it a try!

**Comment by davidecaroselli** [comment]
Found the solution.

**Recovery**
1. you need to uninstall numpy with `pip uninstall numpy` until the error "Cannot uninstall requirement numpy, not installed" is shown, indicating you have no more numpy versions installed.
2. finally install numpy as reported in the INSTALL.md with `pip install numpy==1.14.5`

**Comment by LoekvanKooten** [comment]
I think that's what I did. It was late, maybe I wasn't paying attention, but I had to rinse and repeat several times to get things working. Maybe somewhere a restart is needed, or something was still running in the background.

**Comment by EtienneAb3d** [comment]
Impossible to make MMT 3.3.1 running on Ubuntu 18.04. 
I tried to force python2.7 using conda, uninstall numpy and all cuda, reinstall cuda9 and MMT3.. 
I always get this:
```
Traceback (most recent call last):
  File "./mmt", line 612, in <module>
    main()
  File "./mmt", line 558, in main
    actions[command](args)
  File "./mmt", line 143, in main_create
    builder.resume()
  File "/mnt/SSD/MMT331/ModernMT/cli/mmt/engine.py", line 635, in resume
    self._build(resume=True)
  File "/mnt/SSD/MMT331/ModernMT/cli/mmt/engine.py", line 704, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/mnt/SSD/MMT331/ModernMT/cli/mmt/engine.py", line 498, in __call__
    self._f(*args, **kwargs)
  File "/mnt/SSD/MMT331/ModernMT/cli/mmt/engine.py", line 836, in _prepare_data
    log=log, bpe_symbols=self._bpe_symbols, fromModel=self._fromModel)
  File "/mnt/SSD/MMT331/ModernMT/cli/mmt/engine.py", line 167, in prepare_data
    osutils.shell_exec(command, stdout=log, stderr=log, env=env)
  File "/mnt/SSD/MMT331/ModernMT/cli/libs/osutils.py", line 57, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.libs.osutils.ShellError: Command 't2t-datagen --t2t_usr_dir /mnt/SSD/MMT331/ModernMT/build/lib/t2t --data_dir=/mnt/SSD/MMT331/ModernMT/runtime/SXFR_New/tmp/training/neural_train_data/data --tmp_dir=/mnt/SSD/MMT331/ModernMT/runtime/SXFR_New/tmp/training/neural_train_data/tmp --problem=translate_mmt' failed with exit code 1

```

**Comment by LoekvanKooten** [comment]
The problem is that MTT3 does not support Python 3, and that Anaconda only supports Python 3 these days.

**Comment by EtienneAb3d** [comment]
Definitely, I don't like Python !

I succeeded in creating a Python2 env, like explained here:
https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment/
https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/

As I really need to keep MMT2/3 working, I think I will reinstall all using Ubuntu 16.04, waiting for a real solution for 18.04. But, this is not comfortable in time.

**Comment by EtienneAb3d** [comment]
Problem: on this machine, I can't succeed in updating Ubuntu 16.04. At one time, there is an IPv6 blocking call. In that state, I didn't succeed in installing NVidia drivers.
The only choice I have is to install on 18.04.
:(

**Comment by EtienneAb3d** [comment]
I'm trying to make, at least, my old MMT 3.2.3 models running, starting from a copy of my well installed folder on the old machine to the new Ubuntu 18.04 machine.
I think I got a lot of problem solved. But, now, I find something very strange.
In NeuralDecoder.java:92, the first argument is a JAR path:
`PythonDecoder.Builder builder = new PythonDecoderImpl.Builder(getJarPath(), model);`
But, in PythonDecoderImpl.java, it is supposed to be a pythonExec?
Thus, on line 76, it seems trying to launch some like "python (path)mmt-3.2.3.jar ..":
`ProcessBuilder builder = new ProcessBuilder(command);`
As this code was running properly on the old machine, what can be wrong in this?

**Comment by davidecaroselli** [comment]
> Thus, on line 76, it seems trying to launch something like "python (path)mmt-3.2.3.jar ..":

Yes, that's correct.

> But, now, I find something very strange.

What is the bug you're experiencing, is there an error in log or stdout?

**Comment by EtienneAb3d** [comment]
The log file show this error below. On the first line, you can see that I'm printing the values of the "command" array, with a "python" and then "mmt-3.2.3.jar". 
Remark: I'm currently trying to install MMT 3.3.1.
```
2019-05-09 14:11:44,075 ALL   eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl [pool-7-thread-1] (EM) COMMAND: python /mnt/SSD/MMT323/ModernMT/build/mmt-3.2.3.jar /mnt/SSD/MMT323/ModernMT/engines/SXFR_N06.900K8581/models/decoder --gpu 0
2019-05-09 14:11:44,176 ERROR eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process on GPU 0 failed to start
java.io.IOException: Failed to start neural decoder, received: null
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl.init(PythonDecoderImpl.java:121)
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:92)
	at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.startOnGPU(PythonDecoderImpl.java:53)
	at eu.modernmt.decoder.neural.execution.impl.Handler.restart(Handler.java:55)
	at eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-05-09 14:11:44,177 DEBUG eu.modernmt.cluster.ClusterNode [Thread-1] Cluster node status changed: LOADING -> SHUTDOWN
2019-05-09 14:11:44,177 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2019-05-09 14:11:44,181 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2019-05-09 14:11:44,181 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
	at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:91)
	at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
```
