### ISSUE TITLE
Errors while training engine using example data

### ISSUE THREAD

**Issue by harold1505** [modernmt/modernmt#502]
I get the following error while training a new engine,

```
(harold) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/mmt$ ./mmt create en it examples/data/train/ --train-steps 10000

=========== TRAINING STARTED ===========

ENGINE:   default
LANGUAGE: en > it

(1/4) Cleaning corpora
    (1/6) Cleaning corpora...                                    DONE in 2s
    (2/6) De-duplicate corpora...                                DONE in 0s
    (3/6) Preprocess corpora...                                  DONE in 1s
    (4/6) Creating aligner filter...                             
ERROR Unexpected exception: Command '/media/zlabs-nlp/hdd1/Harold/mmt/build/bin/fa_build -s en -t it -i /media/zlabs-nlp/hdd1/Harold/mmt/runtime/default/tmp/training/_temp_cleaning/preprocessed_corpora -m /media/zlabs-nlp/hdd1/Harold/mmt/runtime/default/tmp/training/_temp_cleaning/aligner/en__it.fam -I 4 --case-insensitive --no-favor-diagonal' failed with exit code 127
```

Thanks in advance.

**Comment by nicolabertoldi** [comment]
To give you more support we should look at the the following logfile
/media/zlabs-nlp/hdd1/Harold/mmt/runtime/default/logs/training.log

Are you sure that installation was fully successful?
Which version of ModernMT are you using?

**Comment by harold1505** [comment]
I'm using mmt version 4.1.2. I'm not sure the installation is successful. Because, i tried installing it using binaries. When i extracted the '.tar' , there was no 'requirements.txt'. So i manually added to that folder before running 'pip3 install -r requirements.txt'. 

Now i'm getting the above stated error while creating the engine. I'm hereby attaching the log file requested.
[training.log](https://github.com/modernmt/modernmt/files/3544573/training.log)

**Comment by nicolabertoldi** [comment]
@harold1505 
as you can see from the log, the library  libicui18n.so.60      is missing

Which OS are you using?
Do you have a different version of this library?


Nicola

**Comment by harold1505** [comment]
I'm using 'Ubuntu 16.04.6 LTS'. Could you suggest me a way to install those missing libraries?

**Comment by nicolabertoldi** [comment]
The ModernMT binaries are suitable for Ubuntu 18.04 as reported in https://github.com/modernmt/modernmt/blob/v4.1.2/INSTALL.md#hardware-requirements

If you want to install on Ubuntu 16.04, you should install ModernMT from the source.

**Comment by harold1505** [comment]
When i installed it from the source, it installed fine. But while training the process hangs,

```
zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ ./mmt create en it examples/data/train --train-steps 1000
An engine named "default" already exists, are you sure you want to overwrite it? [y/N] y

=========== TRAINING STARTED ===========

ENGINE:   default
LANGUAGE: en > it

(1/4) Cleaning corpora
    (1/6) Cleaning corpora...                                    DONE in 2s
    (2/6) De-duplicate corpora...                                DONE in 0s
    (3/6) Preprocess corpora...                                  DONE in 2s
    (4/6) Creating aligner filter...                             DONE in 2s
    (5/6) Scoring corpora...                                     DONE in 0s
    (6/6) Apply aligner-based filter...                          DONE in 0s
(1/4) Cleaning corpora DONE in 8s
(2/4) Creating engine
(2/4) Creating engine DONE in 0s
(3/4) Generating binary archives
    (1/4) Tokenize corpora...                                    DONE in 2s
    (2/4) Training BPE model...                                  DONE in 22s
    (3/4) Encoding training corpora...                           DONE in 0s
    (4/4) Generating binary data...                              DONE in 2s
(3/4) Generating binary archives DONE in 27s
(4/4) Training neural model
    (1/2) Train neural network...                                
^CDONE in 27m 19s
    (2/2) Averaging checkpoints...                               
ERROR Unexpected exception: no checkpoints found in /media/zlabs-nlp/hdd1/Harold/modernmt/runtime/default/tmp/training/_temp_train/nn_model
```

After 30mins, I manually stopped the process and obtained the above error.

Here is the log file which says module mmt not found:
[training (1).log](https://github.com/modernmt/modernmt/files/3545926/training.1.log)

**Comment by nicolabertoldi** [comment]
which version of fairseq and pytorch have been installed?

could you please report the outcome of the following two commands within the conda virtual environment? 
```
pip3 show fairseq
pip3 show torch
```

**Comment by harold1505** [comment]
fairseq:

```
zlabs-nlp@zlabs-nlp:~$ pip3 show fairseq
Name: fairseq
Version: 0.8.0
Summary: Facebook AI Research Sequence-to-Sequence Toolkit
Home-page: https://github.com/pytorch/fairseq
Author: None
Author-email: None
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: cffi, regex, sacrebleu, torch, tqdm, numpy, fastBPE
Required-by: 
```

torch:
```
Name: torch
Version: 0.4.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: 
Required-by: torchvision, fairseq
```

**Comment by nicolabertoldi** [comment]
@harold1505 

very strange that you have these old versions.

ModernMT requires newer versions as reported in `requirements.txt`,
torch 1.0.1
fairseq 0.7.1

Are you sure that you run the whole installation procedure, including `setup.py`, in the corrent environment.

Are you using a virtual environment or not?

**Comment by harold1505** [comment]
Yes, I'm using a conda environment. When i run setup.py i get the following error,

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ python setup.py
ERROR: torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    main()
  File "setup.py", line 236, in main
    pip_install()
  File "setup.py", line 219, in pip_install
    osutils.shell_exec(['pip3', 'install', '-r', requirements_txt], stderr=sys.stderr, stdout=sys.stdout)
  File "/media/zlabs-nlp/hdd1/Harold/modernmt/cli/utils/osutils.py", line 60, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.utils.osutils.ShellError: Command 'pip3 install -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt' failed with exit code 1
```

So i manually installed all the required packages,

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ conda list
# packages in environment at /home/zlabs-nlp/miniconda3/envs/harold1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2019.5.15                     1  
cachetools                3.1.1                    pypi_0    pypi
certifi                   2019.6.16                py37_1  
cffi                      1.12.3                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
fairseq                   0.8.0                    pypi_0    pypi
fastbpe                   0.1.0                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.17.1                   pypi_0    pypi
openssl                   1.1.1c               h7b6447c_1  
pip                       19.2.3                   pypi_0    pypi
portalocker               1.5.1                    pypi_0    pypi
protobuf                  3.9.1                    pypi_0    pypi
pycparser                 2.19                     pypi_0    pypi
python                    3.7.4                h265db76_1  
readline                  7.0                  h7b6447c_5  
regex                     2019.8.19                pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
sacrebleu                 1.3.7                    pypi_0    pypi
setuptools                41.0.1                   py37_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.29.0               h7b6447c_0  
tensorboardx              1.8                      pypi_0    pypi
tk                        8.6.8                hbc83047_0  
torch                     1.2.0                    pypi_0    pypi
tqdm                      4.35.0                   pypi_0    pypi
typing                    3.7.4.1                  pypi_0    pypi
urllib3                   1.25.3                   pypi_0    pypi
wheel                     0.33.4                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
```

**Comment by nicolabertoldi** [comment]
@harold1505 

good to know the this whl  does not work with conda.

By the way, you can overcome the issue as follows:
Edit the `requirements.txt` file, and replace the line 
```
https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
```
with the line
```
torch==1.0.1
```

then rerun setup.py.

If succeeds, please check that the version reported in the requirements are actually installed. You can run the following
```
pip3 show regex sacrebleu cachetools tensorboardX fairseq torch 
```

**Comment by harold1505** [comment]
I have made the change to pytorch and the packages got successfully installed. But, the setup failed to download cassandra,

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ python setup.py
Requirement already satisfied: regex in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 1)) (2019.8.19)
Collecting sacrebleu==1.3.1 (from -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/12/5b/7196b11bca204cb6ca9000b5dc910e809081f224c73ef28e9991080e4e51/sacrebleu-1.3.1.tar.gz
Requirement already satisfied: requests in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 3)) (2.22.0)
Requirement already satisfied: cachetools in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 4)) (3.1.1)
Collecting tensorboardX==1.6 (from -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/5c/76/89dd44458eb976347e5a6e75eb79fecf8facd46c1ce259bad54e0044ea35/tensorboardX-1.6-py2.py3-none-any.whl
Collecting torch==1.0.1 (from -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/4e/ba/d78f35357995297206790fe1af8688bc0403828c90f8e99190035196d56e/torch-1.0.1-cp37-cp37m-manylinux1_x86_64.whl (560.1MB)
     |████████████████████████████████| 560.1MB 133kB/s 
Collecting fairseq==0.7.1 (from -r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 7))
Requirement already satisfied: typing in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from sacrebleu==1.3.1->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 2)) (3.7.4.1)
Requirement already satisfied: idna<2.9,>=2.5 in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from requests->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 3)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from requests->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from requests->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 3)) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from requests->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 3)) (1.25.3)
Requirement already satisfied: protobuf>=3.2.0 in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from tensorboardX==1.6->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 5)) (3.9.1)
Requirement already satisfied: numpy in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from tensorboardX==1.6->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 5)) (1.17.1)
Requirement already satisfied: six in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from tensorboardX==1.6->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 5)) (1.12.0)
Requirement already satisfied: cffi in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from fairseq==0.7.1->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 7)) (1.12.3)
Requirement already satisfied: tqdm in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from fairseq==0.7.1->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 7)) (4.35.0)
Requirement already satisfied: setuptools in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from protobuf>=3.2.0->tensorboardX==1.6->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 5)) (41.0.1)
Requirement already satisfied: pycparser in /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages (from cffi->fairseq==0.7.1->-r /media/zlabs-nlp/hdd1/Harold/modernmt/requirements.txt (line 7)) (2.19)
Building wheels for collected packages: sacrebleu
  Building wheel for sacrebleu (setup.py) ... done
  Created wheel for sacrebleu: filename=sacrebleu-1.3.1-cp37-none-any.whl size=21367 sha256=1fff7769f6dbf176fbca66eb03f826f14fc258d2f0bd488407130b4c3dca7008
  Stored in directory: /home/zlabs-nlp/.cache/pip/wheels/56/c0/fb/1c7f9b3a71f64cdf86291cc645596f71746807bf2f72b3c1dd
Successfully built sacrebleu
Installing collected packages: sacrebleu, tensorboardX, torch, fairseq
  Found existing installation: sacrebleu 1.3.7
    Uninstalling sacrebleu-1.3.7:
      Successfully uninstalled sacrebleu-1.3.7
  Found existing installation: tensorboardX 1.8
    Uninstalling tensorboardX-1.8:
      Successfully uninstalled tensorboardX-1.8
  Found existing installation: torch 1.2.0
    Uninstalling torch-1.2.0:
      Successfully uninstalled torch-1.2.0
  Found existing installation: fairseq 0.8.0
    Uninstalling fairseq-0.8.0:
      Successfully uninstalled fairseq-0.8.0
Successfully installed fairseq-0.7.1 sacrebleu-1.3.1 tensorboardX-1.6 torch-1.0.1
Downloading Cassandra... [                                        ]   0.0% 00:00Downloading Cassandra... [                                        ]   0.0% 00:01Downloading Cassandra... [                                        ]   0.0% 00:02Downloading Cassandra... [                                        ]   0.0% 00:03Downloading Cassandra... [                                        ]   0.0% 00:04Downloading Cassandra... [                                        ]   0.0% 00:05Downloading Cassandra... [                                        ]   0.0% 00:06Downloading Cassandra... [                                        ]   0.0% 00:07Downloading Cassandra... [                                        ]   0.0% 00:08Downloading Cassandra... [                                        ]   0.0% 00:09Downloading Cassandra... [                                        ]   0.0% 00:10Downloading Cassandra... [                                        ]   0.0% 00:11Downloading Cassandra... [                                        ]   0.0% 00:12Downloading Cassandra... [                                        ]   0.0% 00:13Downloading Cassandra... [                                        ]   0.0% 00:14Downloading Cassandra... [                                        ]   0.0% 00:15Downloading Cassandra... [                                        ]   0.0% 00:16Downloading Cassandra... [                                        ]   0.0% 00:17Downloading Cassandra... [                                        ]   0.0% 00:18Downloading Cassandra... [                                        ]   0.0% 00:19Downloading Cassandra... [                                        ]   0.0% 00:20Downloading Cassandra... [                                        ]   0.0% 00:20  ERROR: HTTPConnectionPool(host='mirrors.estointernet.in', port=80): Max retries exceeded with url: /apache//cassandra/3.11.4/apache-cassandra-3.11.4-bin.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99ef096250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f99ef096250>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='mirrors.estointernet.in', port=80): Max retries exceeded with url: /apache//cassandra/3.11.4/apache-cassandra-3.11.4-bin.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99ef096250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    main()
  File "setup.py", line 239, in main
    install_cassandra()
  File "setup.py", line 167, in install_cassandra
    downloader.download('Cassandra', cassandra_apache_path, cassandra_home, expected_file_size=CASSANDRA_FILE_SIZE)
  File "setup.py", line 46, in download
    return self.download_from_mirrors(name, self._get_mirrors(apache_path), destination_folder, expected_file_size)
  File "setup.py", line 61, in download_from_mirrors
    callback=None if expected_file_size is None else _callback)
  File "setup.py", line 139, in _download_from_mirrors
    r = requests.get(mirror, timeout=10, stream=True)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='mirrors.estointernet.in', port=80): Max retries exceeded with url: /apache//cassandra/3.11.4/apache-cassandra-3.11.4-bin.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99ef096250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ pip3 show regex sacrebleu cachetools tensorboardX fairseq torch 
Name: regex
Version: 2019.8.19
Summary: Alternative regular expression module, to replace re.
Home-page: https://bitbucket.org/mrabarnett/mrab-regex
Author: Matthew Barnett
Author-email: regex@mrabarnett.plus.com
License: Python Software Foundation License
Location: /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages
Requires: 
Required-by: 
---
Name: sacrebleu
Version: 1.3.1
Summary: Hassle-free computation of shareable, comparable, and reproducible BLEU scores
Home-page: https://github.com/mjpost/sacrebleu
Author: Matt Post
Author-email: post@cs.jhu.edu
License: Apache License 2.0
Location: /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages
Requires: typing
Required-by: fairseq
---
Name: cachetools
Version: 3.1.1
Summary: Extensible memoizing collections and decorators
Home-page: https://github.com/tkem/cachetools
Author: Thomas Kemmer
Author-email: tkemmer@computer.org
License: MIT
Location: /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages
Requires: 
Required-by: 
---
Name: tensorboardX
Version: 1.6
Summary: TensorBoardX lets you watch Tensors Flow without Tensorflow
Home-page: https://github.com/lanpa/tensorboardX
Author: Tzu-Wei Huang
Author-email: huang.dexter@gmail.com
License: MIT license
Location: /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages
Requires: six, protobuf, numpy
Required-by: 
---
Name: fairseq
Version: 0.7.1
Summary: Facebook AI Research Sequence-to-Sequence Toolkit
Home-page: https://github.com/pytorch/fairseq
Author: None
Author-email: None
License: UNKNOWN
Location: /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages
Requires: tqdm, numpy, cffi, torch, sacrebleu
Required-by: 
---
Name: torch
Version: 1.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/zlabs-nlp/miniconda3/envs/harold1/lib/python3.7/site-packages
Requires: 
Required-by: fairseq
```

Having all the packages installed, i'm still getting error while training,

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ ./mmt create en it examples/data/train --train-steps 1
Traceback (most recent call last):
  File "./mmt", line 80, in <module>
    main()
  File "./mmt", line 28, in main
    from cli import cleaning, datagen, train, create, server, translate, evaluate, memory
  File "/media/zlabs-nlp/hdd1/Harold/modernmt/cli/datagen.py", line 14, in <module>
    from mmt.textencoder import SubwordDictionary
ModuleNotFoundError: No module named 'mmt'
```

**Comment by nicolabertoldi** [comment]
@harold1505 

first of all, one of the component "cassandra" was not installed properly.
This module is not required for training but it is required for runtime translation.
The error says that you your network is unreachable, and Cassandra (as well as an other package) should be downloaded from the web.
Please check why you do not have internet access.

By the way, if you just want to train a system, you can skip the installation of Cassandra (and the other package) as follows
```
python3 setup.py --skip-kafka --skip-cassandra
```

If it succeeds, you have to run the actual installation of ModernMT
```
pushd src
mvn clean install
popd
```

**Comment by harold1505** [comment]
@nicolabertoldi Thanks a lot for your support. I really appreciate it.

Now, the training is done perfectly. 

(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ ./mmt create en it examples/data/train --train-steps 10
```
An engine named "default" already exists, are you sure you want to overwrite it? [y/N] y

=========== TRAINING STARTED ===========

ENGINE:   default
LANGUAGE: en > it

(1/4) Cleaning corpora
    (1/6) Cleaning corpora...                                    DONE in 2s
    (2/6) De-duplicate corpora...                                DONE in 0s
    (3/6) Preprocess corpora...                                  DONE in 1s
    (4/6) Creating aligner filter...                             DONE in 2s
    (5/6) Scoring corpora...                                     DONE in 0s
    (6/6) Apply aligner-based filter...                          DONE in 0s
(1/4) Cleaning corpora DONE in 8s
(2/4) Creating engine
(2/4) Creating engine DONE in 0s
(3/4) Generating binary archives
    (1/4) Tokenize corpora...                                    DONE in 2s
    (2/4) Training BPE model...                                  DONE in 23s
    (3/4) Encoding training corpora...                           DONE in 0s
    (4/4) Generating binary data...                              DONE in 2s
(3/4) Generating binary archives DONE in 28s
(4/4) Training neural model
    (1/2) Train neural network...                                DONE in 33s
    (2/2) Averaging checkpoints...                               DONE in 1s
(4/4) Training neural model DONE in 34s

=========== TRAINING SUCCESS ===========

You can now start, stop or check the status of the server with command:
	./mmt start|stop|status 
```

But error throws while starting the engine.

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ ./mmt startStarting engine "default"...OK
Loading models...FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /media/zlabs-nlp/hdd1/Harold/modernmt/runtime/default/logs/node.log
```
Is it due to absence of cassandra? I assure you that network connection is perfect. I installed kafka, and opennlp downloading (only cassandra i skipped). Is it due to broken link?

**Comment by nicolabertoldi** [comment]
@harold1505 

yes,
at runtime, ModernMT requires cassandra.

Are you able to check from where the setup.py script would download cassandra?

**Comment by harold1505** [comment]
@nicolabertoldi
I have managed to install cassandra too. Installation happened perfectly. Still i'm unable to start the engine.

It says port is already in use. How to change the port?
[node.log](https://github.com/modernmt/modernmt/files/3551721/node.log)

**Comment by nicolabertoldi** [comment]
@harold1505 

the port is in use from another engine probably

you can stop all other running engines listed with
```
./mmt status
```

it is possible that there are "spurious" processes still alive, due to previous wrong start.

kill all the processes related to ModernMT
and remove the whole content of the runtime directory

In this way you should be in a "clean" scenario

**Comment by harold1505** [comment]
I have removed runtime folder and tried. Still no success.

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ ./mmt status
[Engine: "default"]
    REST API:   stopped
    Cluster:    stopped
    Datastream: stopped
    Database:   stopped
```

**Comment by nicolabertoldi** [comment]
@harold1505 

sure that there are no deamon processes
you can check vy 
```
ps aux | grep _YOUR_ACCOUNT_NAME_
```

if no processes related to ModerntMT
remove runtime/default
restart
and send the logfile `runtime/default/logs/node.log`

**Comment by harold1505** [comment]
I have killed all the processes. Still error occurs,

```
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold$ ps aux | grep harold
zlabs-n+  31050  0.0  0.0  14196   944 pts/27   S+   13:16   0:00 grep --color=auto harold
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold$ cd modernmt/
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ rm -r runtime
(harold1) zlabs-nlp@zlabs-nlp:/media/zlabs-nlp/hdd1/Harold/modernmt$ ./mmt start
Starting engine "default"...OK
Loading models...FAIL



ERROR Unexpected exception: failed to start node, check log file for more details: /media/zlabs-nlp/hdd1/Harold/modernmt/runtime/default/logs/node.log
```

[node (1).log](https://github.com/modernmt/modernmt/files/3554404/node.1.log)

**Comment by nicolabertoldi** [comment]
@harold1505 

there is still a process using port 9042.
I suspect that you have spurious processes or spurious daemon engines

if you can,
please remove all engines,
fully clean the directories  "engines" and "runtime",
re-train the engine "default" ,
re-start the engine "default" .

report in separate files the output of the following commands
```
tree runtime/
tree engines/
ps aux | grep 'Harold"
cat runtime/default/logs/node.log
```
assuming that "Harold" is your username, and "default" is the name of the engine

**Comment by harold1505** [comment]
Now it is working fine. Thanks a lot for your kind support. I appreciate a lot.
