### ISSUE TITLE
MMT412: few things

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#503]
I finally took the time to give MMT412 a try (I was still working with MMT323 till now).
1) the "from source" install procedure lacks the "requirements.txt" install command
2) the "requirements.txt" itself didn't worked properly on my Ubuntu 18.04, especially the torch line. I succeeded by manually installing packages each time I got an error on screen.
3) there is no BLEU evaluation while training ? :(
4) on a 100M pairs training set, training stopped after only 12H (using skip cleaning option), with log showing 0.5 epoch, while it took 3 weeks to converge on a plateau with MMT323
5) I can't resume from the ended training, it seems to try restarting all from the very beginning, and complain about the fact that the model file already exists

I will now try to restart all, enforcing to do 10 epochs.

**Comment by mzeidhassan** [comment]
Thanks @EtienneAb3d  for sharing. I was thinking the other day of posting an issue here asking about users' experience using MMT4. 

I would be grateful if you can share your findings in this issue. 

Are you using the same training dataset used in MMT3? If yes, it would be interesting to see which one produces better quality at your end.

Thanks!

**Comment by EtienneAb3d** [comment]
Yes, same data. But, there is a big difference : MMT3 can't disable the data filtering, while I disabled it for MMT4. The major consequence is certainly that MMT4 will be trained with much more sentences, a lot of them being redundancies, while MMT3 removes doubles (as far as I well understood). I want these redundancies, because I want the model to learn the relative probabilities for each kind of formulation variations.

**Comment by EtienneAb3d** [comment]
I got this error:

```
| epoch 006:  134300 / 158923 loss=3.763, nll_loss=2.115, ppl=4.33, wps=14780, ups=2, wpb=8789.105, bsz=778.471, num_updates=928916, lr=3.28104e-05, gnorm=0.853, clip=0.000, oom=0.000, wall=556271, train_wall=512045
Traceback (most recent call last):
  File "/home/cubaix/venvMMT412/bin/fairseq-train", line 10, in <module>
    sys.exit(cli_main())
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/fairseq_cli/train.py", line 321, in cli_main
    main(args)
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/fairseq_cli/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/fairseq_cli/train.py", line 148, in train
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/fairseq_cli/train.py", line 227, in validate
    for sample in progress:
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/fairseq/progress_bar.py", line 186, in __iter__
    for i, obj in enumerate(self.iterable, start=self.offset):
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/fairseq/data/iterators.py", line 35, in __iter__
    for x in self.iterable:
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/home/cubaix/anaconda3/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/cubaix/venvMMT412/local/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 284, in rebuild_storage_fd
    fd = df.detach()
  File "/home/cubaix/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/cubaix/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/cubaix/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 155, in recvfds
    raise EOFError
EOFError
```
Resume is working...

**Comment by EtienneAb3d** [comment]
I'm finally taking the time to test this new MMT4 model, and get this error :
```
java.io.IOException: Failed to start neural decoder, received: ERROR: __init__() got an unexpected keyword argument 'stop_early'
	at eu.modernmt.decoder.neural.queue.PythonDecoderImpl.init(PythonDecoderImpl.java:121)
	at eu.modernmt.decoder.neural.queue.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:92)
	at eu.modernmt.decoder.neural.queue.PythonDecoderImpl$Builder.startOnGPU(PythonDecoderImpl.java:59)
	at eu.modernmt.decoder.neural.queue.Handler.restart(Handler.java:54)
	at eu.modernmt.decoder.neural.queue.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nicolabertoldi** [comment]
@EtienneAb3d 

could you please give us more details?
- command actually run
- logging file

**Comment by EtienneAb3d** [comment]
I was in version 4.1.2. Updating to 4.2 doesn't solve the problem.
```
./mmt start -e FREN_CKS
Starting engine "FREN_CKS"...OK
Loading models...OK

Engine "FREN_CKS" started successfully

You can try the API with:
	curl "http://localhost:10001/translate?q=world&source=en&target=it&context=computer" | python -mjson.tool
```

```
2019-10-03 10:24:52,840 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2019-10-03 10:24:53,583 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.534s
2019-10-03 10:24:53,710 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2019-10-03 10:24:53,896 INFO  eu.modernmt.decoder.neural.queue.DecoderQueueImpl [pool-6-thread-1] Native decoder process on GPU 1 is starting
2019-10-03 10:24:58,999 ERROR eu.modernmt.decoder.neural.queue.DecoderQueueImpl [pool-6-thread-1] Native decoder process on GPU 1 failed to start
java.io.IOException: Failed to start neural decoder, received: ERROR: __init__() got an unexpected keyword argument 'stop_early'
	at eu.modernmt.decoder.neural.queue.PythonDecoderImpl.init(PythonDecoderImpl.java:121)
	at eu.modernmt.decoder.neural.queue.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:92)
	at eu.modernmt.decoder.neural.queue.PythonDecoderImpl$Builder.startOnGPU(PythonDecoderImpl.java:59)
	at eu.modernmt.decoder.neural.queue.Handler.restart(Handler.java:54)
	at eu.modernmt.decoder.neural.queue.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-03 10:24:59,001 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2019-10-03 10:24:59,011 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2019-10-03 10:24:59,011 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
	at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:92)
	at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
```

**Comment by EtienneAb3d** [comment]
With `-v 3` option, nothing more in the LOG file.

**Comment by nicolabertoldi** [comment]
@EtienneAb3d 

I suspect that you are using a version of fairseq which is not compliant with ModernMT.
Currently, ModernMT is compliant with fairseq 0.7.1, and not with the newest fairseq 0.8.

**Comment by EtienneAb3d** [comment]
Thanks ! This seems to solve the problem:
```
pip uninstall fairseq
pip install fairseq==0.7.1
```

**Comment by nicolabertoldi** [comment]
@EtienneAb3d 

good to know!

I am closing the issue.
Feel free please reopen it or open a new one in case of  necessity.
