### ISSUE TITLE
MMT421 : cassandra version hard coded in the model ?

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#520]
When trying to launch a model built with previous version using MMT421, I got this error:
```
2019-11-03 15:09:45,875 ERROR eu.modernmt.cli.ClusterNodeMain [main] Failed to start node
eu.modernmt.engine.BootstrapException: java.io.FileNotFoundException: File '/mnt/SSD/MMT421/modernmt/vendor/cassandra-3.11.4/conf/cassandra.yaml' does not exist
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:36)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:363)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:55)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: java.io.FileNotFoundException: File '/mnt/SSD/MMT421/modernmt/vendor/cassandra-3.11.4/conf/cassandra.yaml' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.lineIterator(FileUtils.java:1856)
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.createConfig(EmbeddedCassandra.java:131)
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:73)
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:32)
	... 3 more
2019-11-03 15:09:45,875 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: java.io.FileNotFoundException: File '/mnt/SSD/MMT421/modernmt/vendor/cassandra-3.11.4/conf/cassandra.yaml' does not exist
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:36)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:363)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:55)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: java.io.FileNotFoundException: File '/mnt/SSD/MMT421/modernmt/vendor/cassandra-3.11.4/conf/cassandra.yaml' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.lineIterator(FileUtils.java:1856)
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.createConfig(EmbeddedCassandra.java:131)
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:73)
	at eu.modernmt.cluster.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:32)
	... 3 more
2019-11-03 15:09:46,049 DEBUG eu.modernmt.cluster.ClusterNode [Thread-1] Cluster node status changed: UPDATED -> SHUTDOWN
```

MMT421 is installing cassandra 3.11.5. I think the cassandra version is hard coded in the model, right ?

Copying cassandra 3.11.4 folder from the old installation to the new one solve the problem.

**Comment by EtienneAb3d** [comment]
In the original post of this issue, I though the cassandra version was hard-coded in my old engine that was requiring an old version of it, but it's only a MMT installation trouble.

I discovered that MMT is reading the cassandra version in the `core/pom.xml`.

When you are re-installing MMT, and cassandra version needs to be changed (like currently: version 3.11.10 is no more available and needs to be upgraded to version 3.11.11) in the `setup.py`, you need to also change it in the `src/core/pom.xml`.

Then update the installation with:
```
cd src
mvn install
```
