### ISSUE TITLE
Different translation for language pair when used in multilingual engine

### ISSUE THREAD

**Issue by ecly** [modernmt/modernmt#531]
I have run into an issue, which I originally discovered in ModernMT 4.2, but which also affects ModernMT 4.5, albeit with a slightly different outcome. In ModernMT 4.2, the error came to light in the form of standalone language pair engine being able to translate a segment just fine, but failing with a 500 error codes in a multilingual setting. It mostly occured for segments containing extremely rare characters, similar to the description in #527 , but I now also experienced an example for FR -> EN with a somewhat standard segment: 
```
Le succès de l'assainissement de l'entité juridique suisse d'une banque d'importance systémique serait ainsi plus probable, ce qui contribuerait à atteindre l'objectif principal, à savoir le maintien ininterrompu des fonctions systémiques.
```
When running the FR -> EN by itself, the result is nice with both MMT 4.2 and 4.5:
```
The success of the reorganisation of the Swiss legal entity of a systemically important bank would thus be more likely, which would contribute to achieving the main objective of uninterrupted maintenance of systemic functions.
```
When using a multilingual engine with MMT 4.2 and a couple of additional language pairs, this results in a 500 error. For some segments, we receive no stacktrace in the logs, for other we get the following:
```
java.lang.ArrayIndexOutOfBoundsException: 33
	at eu.modernmt.processing.WordTextGuessingProcessor.call(WordTextGuessingProcessor.java:21)
	at eu.modernmt.processing.WordTextGuessingProcessor.call(WordTextGuessingProcessor.java:11)
	at eu.modernmt.processing.ProcessingPipeline.call(ProcessingPipeline.java:26)
	at eu.modernmt.processing.VoidProcessingPipeline.call(VoidProcessingPipeline.java:17)
	at eu.modernmt.processing.VoidProcessingPipeline.call(VoidProcessingPipeline.java:9)
	at eu.modernmt.processing.concurrent.PipelineExecutor.process(PipelineExecutor.java:35)
	at eu.modernmt.processing.concurrent.PipelineExecutor.process(PipelineExecutor.java:28)
	at eu.modernmt.processing.Postprocessor.process(Postprocessor.java:45)
	at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:110)
	at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:73)
	at eu.modernmt.api.actions.translation.Translate.execute(Translate.java:43)
	at eu.modernmt.api.actions.translation.Translate.execute(Translate.java:25)
	at eu.modernmt.api.framework.actions.ObjectAction.getResult(ObjectAction.java:13)
	at eu.modernmt.api.framework.actions.ObjectAction.getResult(ObjectAction.java:8)
	at eu.modernmt.api.framework.actions.JSONAction.unsecureExecute(JSONAction.java:52)
	at eu.modernmt.api.framework.actions.JSONAction.execute(JSONAction.java:23)
	at eu.modernmt.api.framework.routing.RouterServlet.service(RouterServlet.java:85)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:205)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at eu.modernmt.api.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

When using a multilingual engine in ModernMT 4.5 instead, it "works" in the sense of not crashing, but the translation is the following:
```
&lt;UNK&gt; &lt;UNK&gt; &lt;UNK&gt; &lt;UNK&gt; &lt;UNK&gt; &lt;UNK&gt; de financiële zekerheid van de systemically important bank would be more likely, which would contribute to achieving the main objective of uninterrupted maintenance of systemic functions.
```
I imagine there is no "easy fix" without a new release of Modern MT, but is this something you have experienced before and are possibly already aware of?

**Comment by ecly** [comment]
@nicolabertoldi @davidecaroselli As a follow up, as we are experiencing this more and more, it feels very much that this bug is related to handling of out-of-vocabulary tokens in multilingual engines.

**Comment by ecly** [comment]
@nicolabertoldi @davidecaroselli I saw some changes in 4.5.2 that I figured could have be related to this, so I tested it. Sadly, this issue is however still present, with same output as 4.5.
