### ISSUE TITLE
Modernmt engine does not start when Aligner is enabled

### ISSUE THREAD

**Issue by parmpreet** [modernmt/modernmt#540]
Hi,
I am trying to setup the MMT engine to use FastAlign for tags projection. I used the data provided in the examples folder to train the modernmt engine for English to Italian. 

My engine.xconf is
```
<node xsi:schemaLocation="http://www.modernmt.eu/schema/config mmt-config-1.0.xsd"
      xmlns="http://www.modernmt.eu/schema/config"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <engine source-language="en" target-language="it">
       <aligner enabled="true"/>
   </engine>
</node>
```
All the training steps completed successfully. But the trained engine fails to start and prints this error in the node.log file
```
2020-06-08 02:38:15,688 INFO  eu.modernmt.cluster.ClusterNode [main] Starting node in cluster "mmt-4.5.8-202006080144" with config:
Node: load-balancing=true
  Network: interface='172.17.0.2', port=5016, host='172.17.0.2'
    Api: enabled=true, port=8045, root='null'
    Join: timeout=5
  Binlog: enabled=true, embedded=true, hosts=localhost, port=9092, name='null'
  Database: embedded=true, enabled=true, type=CASSANDRA, port=9042, host='localhost', name='null', user='null', password='****'
  Engine: name='en_it_aligner', languages=1
    Decoder: queue=400, threads=4, gpus=, class='null', enabled=true, echo=false
    Aligner: enabled=true
    Analyzer: enabled=true, analyze=true, batch=16, threads=4, timeout=30, misalignment=10240
2020-06-08 02:38:15,705 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2020-06-08 02:38:16,690 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.69s
2020-06-08 02:38:16,848 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2020-06-08 02:38:16,850 INFO  eu.modernmt.engine.Engine [main] Loading default pre-processing configuration
2020-06-08 02:38:16,868 INFO  eu.modernmt.engine.Engine [main] Loading default post-processing configuration
2020-06-08 02:38:16,898 ERROR eu.modernmt.cli.ClusterNodeMain [main] Failed to start node
eu.modernmt.engine.BootstrapException: Failed to instantiate aligner
	at eu.modernmt.engine.Engine.load(Engine.java:107)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:278)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:58)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:188)
Caused by: java.io.IOException: Could not load any FastAlign model from path /workspaces/modernmt/engines/en_it_aligner/models/aligner
	at eu.modernmt.aligner.fastalign.FastAlign.<init>(FastAlign.java:93)
	at eu.modernmt.engine.Engine.load(Engine.java:105)
	... 3 more
```
MMT engine still fails to start after creating the `aligner` folder at the correct location. Now it gives this error

```
2020-06-08 02:38:16,899 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: Failed to instantiate aligner
	at eu.modernmt.engine.Engine.load(Engine.java:107)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:278)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:58)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:188)
Caused by: java.io.IOException: Could not load any FastAlign model from path /workspaces/modernmt/engines/en_it_aligner/models/aligner
	at eu.modernmt.aligner.fastalign.FastAlign.<init>(FastAlign.java:93)
	at eu.modernmt.engine.Engine.load(Engine.java:105)
	... 3 more
```

I am using this command to start the engine.

```
./mmt start -e en_it_aligner
```

Attaching the training log for more information
[training.log](https://github.com/modernmt/modernmt/files/4748410/training.log)

Could you please provide me more information about how to fix this issue.

**Comment by davidecaroselli** [comment]
Hi @parmpreet 
New version of ModernMT is not using FastAlign for alignment anymore, instead it uses the Neural Network attention model. For this reason the Aligner **is no longer trained during engine creation**. That’s why ModernMT is complaining: it cannot find the Aligner model

**Comment by parmpreet** [comment]
Thanks for the reply.
Could you please let me know the last version that used the FastAlign?

**Comment by nicolabertoldi** [comment]
The latest release using FastAlign for generating the alignment between source and target is lost lost in the mists of time; it should be *v2.5*.
Pleas, take into account that we do not provide any support about so old code.

**Comment by parmpreet** [comment]
Thanks
