### ISSUE TITLE
Severe showstopper bug in fairseq

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#562]
`loek@DORAEMON:~/modernmt4$ ./mmt create zh en data/proceng -e proceng --gpus 0 --resume

=========== TRAINING STARTED ===========

ENGINE:   proceng
LANGUAGE: zh > en

(1/4) Cleaning corpora
(1/4) Cleaning corpora SKIPPED
(2/4) Creating engine
(2/4) Creating engine SKIPPED
(3/4) Generating binary archives
(3/4) Generating binary archives SKIPPED
(4/4) Training neural model
    (1/2) Train neural network...                                
ERROR Unexpected exception: Command 'fairseq-train /home/loek/modernmt4/runtime/proceng/tmp/training/data_generated --save-dir /home/loek/modernmt4/runtime/proceng/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt4/build/mmt-4.5.4.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt4/runtime/proceng/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas (0.9, 0.98) --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10' failed with exit code 1
loek@DORAEMON:~/modernmt4$ fairseq-train /home/loek/modernmt4/runtime/proceng/tmp/training/data_generated --save-dir /home/loek/modernmt4/runtime/proceng/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt4/build/mmt-4.5.4.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt4/runtime/proceng/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas '(0.9,0.98)' --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10
| NOTE: you may get better performance with: --ddp-backend=no_c10d
| distributed init (rank 0): tcp://localhost:13410
| distributed init (rank 1): tcp://localhost:13410
| initialized host DORAEMON as rank 1
| initialized host DORAEMON as rank 0
Namespace(activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9,0.98)', adam_eps=1e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, arch='transformer_mmt_base', attention_dropout=0.1, bucket_cap_mb=25, clip_norm=0.0, cpu=False, criterion='label_smoothed_cross_entropy', curriculum=0, data='/home/loek/modernmt4/runtime/proceng/tmp/training/data_generated', dataset_impl='mmap', ddp_backend='c10d', decoder_attention_heads=8, decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim=2048, decoder_input_dim=512, decoder_layers=6, decoder_learned_pos=False, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method='tcp://localhost:13410', distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=2, dropout=0.3, encoder_attention_heads=8, encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=2048, encoder_layers=6, encoder_learned_pos=False, encoder_normalize_before=False, find_unused_parameters=False, fix_batches_to_gpus=False, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, global_sync_iter=10, keep_interval_updates=10, keep_last_epochs=10, label_smoothing=0.1, lazy_load=False, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=100, lr=[0.0005], lr_scheduler='inverse_sqrt', max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=3072, max_update=0, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, no_epoch_checkpoints=False, no_progress_bar=True, no_save=False, no_token_positional_embeddings=False, num_workers=0, optimizer='adam', optimizer_overrides='{}', raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='/home/loek/modernmt4/runtime/proceng/tmp/training/_temp_train/nn_model', save_interval=1, save_interval_updates=1000, seed=1, sentence_avg=False, share_all_embeddings=True, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='mmt_translation', tbmf_wrapper=False, tensorboard_logdir='/home/loek/modernmt4/runtime/proceng/tmp/training/_temp_train/tensorboard_logdir', threshold_loss_scale=None, train_subset='train', update_freq=[4], upsample_primary=1, use_bmuf=False, user_dir='/home/loek/modernmt4/build/mmt-4.5.4.jar/mmt', valid_subset='valid', validate_interval=1, warmup_init_lr=1e-07, warmup_updates=4000, weight_decay=0.0)
| [sl] dictionary: 31680 types
| [tl] dictionary: 31680 types
| /home/loek/modernmt4/runtime/proceng/tmp/training/data_generated valid sl-tl 310 examples
TransformerModel(
  (encoder): TransformerEncoder(
    (embed_tokens): Embedding(31680, 512, padding_idx=1)
    (embed_positions): SinusoidalPositionalEmbedding()
    (layers): ModuleList(
      (0): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (1): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (2): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (3): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (4): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (5): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (decoder): TransformerDecoder(
    (embed_tokens): Embedding(31680, 512, padding_idx=1)
    (embed_positions): SinusoidalPositionalEmbedding()
    (layers): ModuleList(
      (0): TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (encoder_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (encoder_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (1): TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (encoder_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (encoder_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (2): TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (encoder_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (encoder_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (3): TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (encoder_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (encoder_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (4): TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (encoder_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (encoder_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (5): TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (encoder_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (encoder_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
        (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
)
| model transformer_mmt_base, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 60358656 (num. trained: 60358656)
| training on 2 GPUs
| max tokens per GPU = 3072 and max sentences per GPU = None
| NOTICE: your device may support faster training with --fp16
Traceback (most recent call last):
  File "/home/loek/.local/bin/fairseq-train", line 11, in <module>
    sys.exit(cli_main())
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 298, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/loek/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/loek/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/loek/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 265, in distributed_main
    main(args, init_distributed=True)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 68, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 107, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/trainer.py", line 175, in load_checkpoint
    self.optimizer.load_state_dict(last_optim_state, optimizer_overrides)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/optim/fairseq_optimizer.py", line 65, in load_state_dict
    self.optimizer.load_state_dict(state_dict)
  File "/home/loek/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 147, in load_state_dict
    state[param] = cast(param, v)
  File "/home/loek/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 134, in cast
    return {k: cast(param, v) for k, v in value.items()}
  File "/home/loek/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 134, in <dictcomp>
    return {k: cast(param, v) for k, v in value.items()}
  File "/home/loek/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 131, in cast
    value = value.to(param.device)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 808.67 MiB already allocated; 15.12 MiB free; 17.33 MiB cached)
`

**Comment by LoekvanKooten** [comment]
[training.log](https://github.com/modernmt/modernmt/files/5286276/training.log)

**Comment by LoekvanKooten** [comment]
I should add that I've tried several other things already, like reducing max-tokens all the way to 20. Same issue. Forcing fairseq to use two GPU's. Same issue. Using memory-efficient-fp16. --skip-invalid-size. Same issue. It gets stuck on something, and I don't know what it is.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
The training log is quite strange. It show several training which started 
```
2020-09-26 01:05:08,512 [INFO] - Training step "train_nn" started
2020-09-26 07:53:30,743 [INFO] - Training step "train_nn" started
2020-09-26 08:03:45,184 [INFO] - Training step "train_nn" started
```
But none of this terminates neither with error or averaging.
Only the last "start" reports errors.

Is it possible that the you run more training contemporarily?

Please try to run a new training.
But before start it, please remove completely the directories ``/home/loek/modernmt4/runtime/proceng/`` and ``/home/loek/modernmt4/engines/proceng/``.
Please, be sure that you GPU are totally free with the command ```nvidia-smi```.

Does the error occur again? Which is the the log in this case?

**Comment by LoekvanKooten** [comment]
The first one is valid. Everything after that were just trials to do another start after the system crashed with a fairseq error. All of them failed, as you can see. The system converged to a loss of about 6, could go down a lot further (most of my trainings converge around 2) but it was impossible to continue the training. The training was started at 1 AM on an empty and totally clean system that ran many succesful trainings before. The next morning I found that the system had reset. This sometimes happens. The training was done on 1 gpu; there is no overheating and there is more than enough power. If you can't find any errors before the restart at 8 AM, it means the system just crashed, before it had even time before writing an error in the log.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

But why are there two restarts at 08:03 and 08:14, which actually restarted correctly?
Are they due a crash and shutdown of the system?
If so, I would suggest to investigate why your machine crashes; it should be due to ModernMT. 

It is possible that, if the last crash happened during the saving of a checkpoint, the file is incorrectly written, and consequently the system cannot load it consistently.

You could try to remove the last checkpoint, and copy the second last checkpoint into ``checkpoint_last.pt``, which is the one which is read at restart.

**Comment by LoekvanKooten** [comment]
The last crashes were not hard crashes, but soft crashes, related to fairseq complaining about having too little memory (while the graphics card has about 11 GB on board and wasn't used for other things). Let me try to remove that last checkpoint and see what happens.

**Comment by LoekvanKooten** [comment]
The second time I had two hard crashes (at different points), but I was able to continue the training after each reset. Does the training goes differently each time? I.e. does the system pick new random sets each time?

I'm beginning to think this may be a sync issue. Maybe fairseq really doesn't like two different graphics cards from two different brands sitting on the same motherboard, even if you use ==gpus 0. What do you think?

As the system crashed all the time anyway when not using ==gpus 0, I've taken out the second graphics card. The first card is going to be replaced by a RTX 3090 soon anyway.

Please let me know your thoughts.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

sincerely we never tried ModernMT with multiple GPU of different type. So I cannot say anything.
What fairseq developers say about?

Which type of GPUs 
are you using?

**Comment by LoekvanKooten** [comment]
That was an Inno3D 1080 TI and a Gigabyte GeForce AORUS RTX 2080 Ti XTREME 11G.

I haven't asked the developers of fairseq yet. I'll do that.

**Comment by LoekvanKooten** [comment]
It's happening again, with just one 2080 Ti. So it's not heat or whatsoever. It's fairseq crashing on certain datasets. Fairseq itself by the way is not giving any response or whatsoever. 

[training.log](https://github.com/modernmt/modernmt/files/5316426/training.log)

**Comment by LoekvanKooten** [comment]
Deleting the last checkpoints does not help. GPU's were clean (entire system was restarted), runtime directory was empty. I've done everything.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
This is clearly a problem of fairseq and not of ModernMT, so maybe it is better if you ask he fairseq support team.

Maybe you can try to add this parameter:
```--ddp-backend=no_c10d```

**Comment by LoekvanKooten** [comment]
The extra parameter gives the same result, I'm afraid. Fairseq is not responding. I'm stuck.

**Comment by LoekvanKooten** [comment]
Another issue opened at https://github.com/pytorch/fairseq/issues/2684 but it will take ages until we get an answer, if ever. They've been putting issues in triage for weeks already.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
I suspect that something in your data makes the system crazy.


If you are able to reproduce the error with a small training data, and if you could pass me these data, I could try to reproduce the error on my machine and investigate the issue.

**Comment by LoekvanKooten** [comment]
I'll send you the files in question! It's a small dataset (and in fact, it seems like this happens more often in smaller datasets).

**Comment by LoekvanKooten** [comment]
Okay, I don't know why it resets, but I think there is a workaround, which you, the developers can implement.

When the computer crashes (hard reset), fairseq doesn't start anymore. I think this is because in the runtime/training directory's subdirectories (multiple of them!), there are now several files of 0 KB. When I delete all of them, training seems to resume.

As for when the computer crashes. It happens mainly with:
1. Small datasets
2. Especially when the source language is Asian (especially Korean)

**Comment by LoekvanKooten** [comment]
And THEN there's this other really mysterious bug, which also happens in the same scenario:

ModernMT quits with:
(1/2) Train neural network...                                
ERROR Unexpected exception: could not find "loss" value in event file: /home/loek/modernmt4/runtime/engkor/tmp/training/_temp_train/tensorboard_logdir/valid/events.out.tfevents.1601711950.DORAEMON

BUT!

The training actually continues on the background. Checkpoints are added, the loss value on Tensorboard keeps going down... it's just that ModernMT has returned to the prompt, so that the training can never be stopped anymore.

The plot thickens.
