### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: 

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#573]
Trying ModernMT on a 3090 here. All seems to be working, but during trianing I get:

model transformer_mmt_base, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 60874752 (num. trained: 60874752)
| training on 1 GPUs
| max tokens per GPU = 3072 and max sentences per GPU = None
| no existing checkpoint found /home/loek/modernmt4/runtime/japduttest/tmp/training/_temp_train/nn_model/checkpoint_last.pt
| loading train data for epoch 0
| /home/loek/modernmt4/runtime/japduttest/tmp/training/data_generated train sl-tl 70032 examples
| NOTICE: your device may support faster training with --fp16
Traceback (most recent call last):
  File "/home/loek/.local/bin/fairseq-train", line 11, in <module>
    sys.exit(cli_main())
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 302, in cli_main
    main(args)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/trainer.py", line 283, in train_step
    raise e
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/trainer.py", line 260, in train_step
    ignore_grad
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/tasks/fairseq_task.py", line 234, in train_step
    optimizer.backward(loss)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/optim/fairseq_optimizer.py", line 74, in backward
    loss.backward()
  File "/home/loek/.local/lib/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/loek/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [25, 104, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by LoekvanKooten** [comment]
Or I guess the real question should be:

How to get this thing running with a 3090? What exact combination of CUDA, cuDN, NVIDIA drivers, fairseq etc. do I need?

**Comment by LoekvanKooten** [comment]
No longer applicable.
