### ISSUE TITLE
ModernMT does not run on Geforce 30 series - verified with clean installation

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#574]
@davidecaroselli 

1. Back-up your existing engines so that you can copy them back later.
2. Reinstall Ubuntu 18.02 from a USB stick.
3. Do not install the newest NVIDIA drivers via the NVIDIA website. 
4. Instead install CUDA 11.1 (the only version compatible with the 455.32 drivers needed for your RTX 3090) straight away via the same website. This installation includes the drivers (455.32). Contrary to 3), these will work on Ubuntu.
5. Install cuDNN 8.0.4 via the NVIDIA website (the only version compatible with CUDA 11.1).
6. Follow rest of installation instructions. 

Card is detected as GPU 0 in nvidia-smi. No errors anywhere or whatsoever.

Starting engine "engdut".... OK
Loading models...

(The end - nothing ever happens - it gets stuck here)

**Comment by LoekvanKooten** [comment]
@davidecaroselli @nicolabertoldi Can you at least let me know when this issue can be solved? Else I will need to take out the 3090 again and re-install the 2080, as this is a production machine which really needs to work before tomorrow morning again. Thank you in advance!

**Comment by LoekvanKooten** [comment]
Okay, it was worth a try. Removing graphics card, reinserting the old 2080. Please let me know when this issue is solved; I won't be able to test until next Sunday though.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

actually we never tried testing our software on the RTX3-30 series.
So we do not know which is the right configuration you require.

Concerning GEForce 2080 Ti, the requirements and settings reported in the installation guidelines of the latest version work fine.

Ubuntu 18.04
Java 8
Python 3.6 (or higher)
CUDA Toolkit 10.1
libcudnn7_7.6.5
torch==1.3.0
fairseq==0.7.1

please feel free to close the issue it this works for you as well.

**Comment by LoekvanKooten** [comment]
Thank you for your reply!. No, that does not work. Definitely not. The 30 series require 455.32 drivers, which require CUDA 11.1, which requires cuDNN 8.0.4. 

I'd definitely start testing this, as the speed increase during training can be enormous!

Are there any plans for this?

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

we do not have short-time plan to test ModernMT on this kind of GPUs (especially because we not such GPU available) and modified the code to be compliant with CUDA 11.1 and cuDNN 8.0.4 and 455.32 drivers.

We are thinking to move ModernMT to work with more recent version of fairseq, but we cannot say an expected time.

You said "the speed increase during training can be enormous"; could you please report some figures about that? Which is the GPU you compared to?

**Comment by LoekvanKooten** [comment]
That would be a 2080 RTX versus a 3090 RTX. 

https://gpu.userbenchmark.com/Compare/Nvidia-RTX-3090-vs-Nvidia-RTX-2080-Ti/4081vs4027#:~:text=The%203090%20offers%20more%20than,find%20value%20in%20the%203090.

Or am I totally wrong?

**Comment by LoekvanKooten** [comment]
@nicolabertoldi Please consider doing this. It may be just a few small adjustments in the code, I don't know. It could potentially shorten 3 days training time for a medium engine to 2 days or less, which is considerable, I think.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

I think that a right comparison should be done on a real ModernMT training/translation task. Not always the declared speedups correspond to real gains.

Furthermore, the 3090 has a double speed, but it costs twice. So for the sake of ModernMT training nothing changes, assuming you buy two 2080Ti GPUs and use the same model size.


By the way moving to newer fairseq is in out to-do list.

**Comment by LoekvanKooten** [comment]
@nicolabertoldi Not all systems can fit two 2080's ;-) Also, at least on my system, using multiple GPU's made it very unstable. Please refer to https://github.com/modernmt/modernmt/issues/559

**Comment by LoekvanKooten** [comment]
That, plus the fact that the 30 series is the new standard from now on and the 20 series is being phased out. Last but not least, lower cards in this series (the 3070 for example) offer twice the performance of a 2080 for half the price! That's a pretty compelling argument, I'd say.

**Comment by EtienneAb3d** [comment]
> @nicolabertoldi Thank you for your reply!. No, that does not work. Definitely not. The 30 series require 455.32 drivers, which require CUDA 11.1, which requires cuDNN 8.0.4.

I have currently MMT running with a 455.32 driver and CUDA 11.1, but on a 2080Ti (I don't know for 30 series):
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:09:00.0 Off |                  N/A |
| 72%   66C    P2    60W / 250W |   8823MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:43:00.0 Off |                  N/A |
| 39%   50C    P2    64W / 250W |   5747MiB / 11018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

It was a progressive upgrade, thus possibly older versions are also installed with their dependences.

You can install older CUDA version over newer ones, this works (see https://github.com/modernmt/modernmt/issues/482).

**Comment by LoekvanKooten** [comment]
Yes, with the 2080 Ti this works. I have tried that. Unfortunately, the 30 series changes all that.

As for now, this is how this ends (funny story).

https://www.linkedin.com/feed/update/urn:li:activity:6729815974389919744/

But I'd rather see another solution :)

**Comment by EtienneAb3d** [comment]
> Yes, with the 2080 Ti this works. I have tried that. Unfortunately, the 30 series changes all that.

Reading your discussion, I'm not sure we are really on the same line. Did you really do this, in this order:
1) install Nvidia 455.32 drivers with its required CUDA 11.1 and cuDNN 8.0.4
2) install over it older CUDA 10.1 with cuDNN 7.6.5 as listed in the MMT requirements
3) install MMT itself

**Comment by LoekvanKooten** [comment]
This may work, but the only reason why it may work, is that ModernMT then uses CUDA 10.1, which does not address the Ampere architecture of the 30 series. So in a best-case scenario this would make the 30-series run as a 20-series, offering no speed advantage. 

Or am I totally wrong?

**Comment by EtienneAb3d** [comment]
I think, if it's really a question of card architecture, it wont' work.

If it works:
- it means there is just a question of lib dependences that could be solved by installing CUDA 11 before CUDA 10 (as I did in the above quoted post)
- you will get much more CUDA cores with the 3090 than with the 2080, thus much calculation power, especially for the training config
- yo also will get much more G-RAM, thus wil lbe able to load more models on a single card in a production config

**Comment by LoekvanKooten** [comment]
I did get the card to work during the first try, after installing and reinstalling stuff for like 8 hours at a stretch. So yes, there is a dependency problem somewhere. In the end however, that led to this problem in fairseq: https://github.com/pytorch/fairseq/issues/2842

Loading models was possible, but training always went wrong when trying to set up the decoder.

**Comment by EtienneAb3d** [comment]
Ok, it's up to you to take the time for this test or not. I do not have a 3090 on my side.
Playing Modern Warfare with 600 FPS is also nice.
:D

**Comment by LoekvanKooten** [comment]
LOL 👍 

As said, I tested that. We really need ModernMT to come up with a solution, and somehow get them to understand why it's a really bad idea to ignore the 30 series.

**Comment by EtienneAb3d** [comment]
You tested **exactly** what I suggested? It's not really clear in all your past explanations.

**Comment by LoekvanKooten** [comment]
I did that yesterday, but as soon as I installed CUDA 7.5.6, the card went blank and I only got a low-res screen in Ubuntu. X-Server was no longer working and ModernMT saw no GPU.

It's clear that Ubuntu itself isn't completely ready for the 30 series yet either.

**Comment by LoekvanKooten** [comment]
Basically I got the best result during the first try, but I have no idea what I was doing there. That was just 8 hours of installing, de-installing and re-installing everything, from drivers to CUDA to cuDNN fo fairseq to Py-torch. And then *snap* suddenly models were loading. But then it turned out it was merely using the CPU.

**Comment by LoekvanKooten** [comment]
@davidecaroselli @nicolabertoldi 

I'm still waiting for an answer :) I think I gave you a very compelling argument for supporting the 30 series. Please include support! If you're not convinced yet, please read the below.

https://www.pcgamer.com/nvidia-rtx-3080-review-founders-edition-benchmarks/

"It feels almost redundant to call the new Nvidia RTX 3080 the fastest graphics card you can buy. I mean, today, it absolutely is, and after the first reveal that was pretty much inevitable. The initial performance figures from the green team's grand unveiling were no joke: this thing takes the RTX 2080 Ti outside and gives it a good, sound kicking. It's not even close.

The ol' Turing GPU's now whimpering in the corner, its vapour chambers leaking out over my floor as its fans fitfully spin their last.

Which is a pretty spectacular result when you consider the top-end Turing chip was the previous holder of the 'fastest graphics card' title, with its bold specs list and $1,200 sticker price. The fact this $699 card can make such a performance step up, at the same price as the RTX 2080 Super it's replacing, is incredible.

It's at once testament to the new Nvidia Ampere architecture, the work its engineers have put in, and maybe to the more competitive landscape of 2020."

**Comment by LoekvanKooten** [comment]
@EtienneAb3d 

Thinking that maybe, somewhere, I made a mistake, I reinstalled Ubuntu, put brand-new NVIDIA drivers on it, then once more did *exactly* as you stated, *exactly* in the order you stated.

When I start an engine, it says:
Loading models...

The fans spin up.
The fans spin down.
The fans spin up.
The fans spin down.
The fans spin up.
The fans spin down.
The fans spin up.
The fans spin down.
Et cetera.

But the model is not loaded.

No error message.

It's a fact. The 3090 does not work with ModernMT. It does not.

**Comment by EtienneAb3d** [comment]
Ok. Nice to know before buying a 30XX card !
:-/

**Comment by LoekvanKooten** [comment]
@davidecaroselli @nicolabertoldi 

Are you discontinueing this product? I'm not the first one asking on this forum, but just like others I've noticed that many messages get very late responses, or no response at all. What's the purpose of a forum if the users don't get any response from the devs anyway?

If this is a matter of not having a good enough ROI on this forum, as said before, I'm willing to pay for a license (as long as it's a 3 digit number) if that means getting quicker and better support.

I'd be much obliged!

I once more notice that the multiple GPU set-up I'm forced to use now results in constant system crashes due to timing issues (not power issues). I'm now forced to train on 1 2080 RTX while I have a very beefy 3090 RTX laying right beside me.

Please let us know when you will implement support for the 30 series. As stated above, there are some very compelling arguments (please read them).

**Comment by dagid4** [comment]
Today we get our new machine with 2x RTX 3090... Same problem as mentioned.

I'm going to investigate it more. But it's very sad to see ModernMT ignoring new GPU series.

**Comment by dagid4** [comment]
I will be posting updates about my findings.

- RTX 3090 first support was added in NVIDIA driver 455.23.04 (see [release](https://www.nvidia.com/Download/driverResults.aspx/163518/en-us))
- only CUDA 11.1 is compatible with 455 driver (see [compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-application-compatibility))
- official Pytorch binaries doesn't currenly support CUDA 11.1 (see [issue](https://github.com/pytorch/pytorch/issues/47109#issuecomment-719465457))
- unofficial Lambda Stack package for Ubuntu 20.04 claims support for CUDA v11.1, PyTorch v1.6.0, cuDNN v7.6.5 (see [blog](https://lambdalabs.com/blog/install-tensorflow-and-pytorch-on-rtx-30-series/))
- ModernMT requires Pytorch 1.3.0 (see [requirements](https://github.com/modernmt/modernmt/blob/master/requirements.txt))
- ModernMT requires tensorboardX 1.6 and fairseq 0.7.1 (see [requirements](https://github.com/modernmt/modernmt/blob/master/requirements.txt)) but both are Pytorch dependent

If we can update ModernMT to support Pytorch 1.6.0, this could bring us a hope.

**Comment by dagid4** [comment]
So far I have done following.

1. Download Ubuntu 20.04 LTS ([link](https://releases.ubuntu.com/20.04/))
2. Flash USB drive with Ubuntu image using ([balenaEtcher](https://releases.ubuntu.com/20.04/))
3. Install Ubuntu (and fix [problem](https://askubuntu.com/questions/1267212/ethernet-connection-not-working-on-ubuntu-20-04) with network)
4. Update Ubuntu using Software Updater and restart
5. Install NVIDIA driver `sudo apt install nvidia-driver-455` ([link](https://askubuntu.com/a/1295067)) and restart
6. Install Lambda stack ([link](https://lambdalabs.com/blog/install-tensorflow-and-pytorch-on-rtx-30-series/))
```bash
LAMBDA_REPO=$(mktemp) && \
wget -O${LAMBDA_REPO} https://lambdalabs.com/static/misc/lambda-stack-repo.deb && \
sudo dpkg -i ${LAMBDA_REPO} && rm -f ${LAMBDA_REPO} && \
sudo apt-get update && sudo apt-get install -y lambda-stack-cuda
```
7. Install java `sudo apt install -y openjdk-8-jdk`
8. Install development tools `sudo apt install -y git maven cmake libboost-all-dev zlib1g-dev libbz2-dev`
9. Clone ModernMT `git clone https://github.com/modernmt/modernmt.git modernmt && cd modernmt`
10. Remove `torch==1.3.0` line from requirements.txt
11. Run installation script `python3 setup.py`
12. Compile binaries
```bash
pushd src
mvn clean install
popd
```

Compilation was successful. Now the funny part `./mmt create en it examples/data/train/ --train-steps 10000`
<details><summary>click to see whole output</summary>
<pre>
=========== TRAINING STARTED ===========

ENGINE:   default
LANGUAGE: en > it

(1/4) Cleaning corpora
    (1/6) Cleaning corpora...                                    DONE in 1s
    (2/6) De-duplicate corpora...                                DONE in 0s
    (3/6) Preprocess corpora...                                  DONE in 0s
    (4/6) Creating aligner filter...                             DONE in 0s
    (5/6) Scoring corpora...                                     DONE in 0s
    (6/6) Apply aligner-based filter...                          DONE in 0s
(1/4) Cleaning corpora DONE in 3s
(2/4) Creating engine
(2/4) Creating engine DONE in 0s
(3/4) Generating binary archives
    (1/4) Tokenize corpora...                                    DONE in 1s
    (2/4) Training BPE model...                                  DONE in 8s
    (3/4) Encoding training corpora...                           DONE in 0s
    (4/4) Generating binary data...                              DONE in 0s
(3/4) Generating binary archives DONE in 11s
(4/4) Training neural model
    (1/2) Train neural network...                                
ERROR Unexpected exception: Command 'fairseq-train /home/nmtuser/Documents/modernmt/runtime/default/tmp/training/data_generated --save-dir /home/nmtuser/Documents/modernmt/runtime/default/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/nmtuser/Documents/modernmt/build/mmt-4.9.4.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/nmtuser/Documents/modernmt/runtime/default/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --max-update 10000 --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas (0.9, 0.98) --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10' failed with exit code 1

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/nmtuser/.local/lib/python3.8/site-packages/fairseq_cli/train.py", line 265, in distributed_main
    main(args, init_distributed=True)
  File "/home/nmtuser/.local/lib/python3.8/site-packages/fairseq_cli/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/home/nmtuser/.local/lib/python3.8/site-packages/fairseq_cli/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/home/nmtuser/.local/lib/python3.8/site-packages/fairseq/trainer.py", line 283, in train_step
    raise e
  File "/home/nmtuser/.local/lib/python3.8/site-packages/fairseq/trainer.py", line 258, in train_step
    loss, sample_size, logging_output = self.task.train_step(
  File "/home/nmtuser/.local/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 234, in train_step
    optimizer.backward(loss)
  File "/home/nmtuser/.local/lib/python3.8/site-packages/fairseq/optim/fairseq_optimizer.py", line 74, in backward
    loss.backward()
  File "/usr/lib/python3/dist-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/lib/python3/dist-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
</pre>
</details>

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [26, 112, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

This could be incompatibility between fairseq 0.7.1 and Pytorch 1.6.0 or ModernMT uses fairseq in a way, which is no longer valid (see [link](https://discuss.pytorch.org/u/111367)). Now I have to decide, upgrade fairseq or resolve errors. What do you think? 

I'm trying to fix the errors.

**Comment by dagid4** [comment]
I have upgraded to fairseq 0.10.1 and tensorboardX 2.1. Also fixed some import module routine. After running the training, PC has gone loud!!! That is a good sign.

Additional steps required:

10. Remove `torch==1.3.0` line from requirements.txt and change versions `tensorboardX==2.1` `fairseq==0.10.1`
13. Edit `~/.local/lib/python3.8/site-packages/fairseq/utils.py` change lines 441-444 from upper to lower:
```
            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            else:
```
```
            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            module_parent, module_name = os.path.split(module_path)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            elif not os.path.exists(module_parent):
```
14. Run the training `./mmt create en it examples/data/train/ --train-steps 10000`

**Comment by davidecaroselli** [comment]
Hi all!

We have just released the support to CUDA 11 in the latest `master` commit!
We tested ModernMT on the new NVIDIA A100 with CUDA 11, PyTorch 1.7.1, and Fairseq 0.10.1.
In order to make ModernMT work with this configuration you will have to:

1. Install CUDA 11 (these are the only ones compatible with new NVIDIA chips)
2. install the new python dependencies: `pip3 install -r requirements_cuda-11.txt` (we recommend using a **virtualenv**)

ModernMT will automatically detect it is running with the newest Fairseq. However, this feature must be considered experimental for the moment because, unfortunately, we found out that:

1. Due to an issue with Fairseq 0.10.1 **training won't work for the moment**. We have already sent a pull request to Fairseq team and they have merged it! So it should be part of the next release of Fairseq.
2. Most importantly, we measured that the new Fairseq is **significantly slower** than its predecessor 0.7.1. So, at the end of the day, the **A100 performed much worse in terms of speed compared to V100**.

**Comment by LoekvanKooten** [comment]
Ouch. So basically the best is to wait until the new architecture actually becomes faster?

**Comment by dagid4** [comment]
I can confirm that ModernMT translation is working on RTX 3090 now. 

I have encountered some errors while trying to install:
- before running `pip3 install -r requirements_cuda-11.txt` run `pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html` otherwise error occurs
- setup.py had to be modified on line 218 instead of `requirements.txt` place `requirements_cuda-11.txt`

It seems you don't need to install CUDA or CUDNN, because PyTorch have everything contained. I've only installed the GPU driver `sudo apt install nvidia-driver-455`.

**Comment by LoekvanKooten** [comment]
How's speed compared to before?

**Comment by dagid4** [comment]
I have run test translation with approx. 2000 character. The PC with 2x RTX 2080 Ti responded after 2.49s and the PC with 2x RTX 3090 responded after 2.71s. It seems there is about 10% performance dropdown.

**Comment by LoekvanKooten** [comment]
Thank you very much for that insight! How about training?

**Comment by dagid4** [comment]
I didn't tried yet, but according to 
> Due to an issue with Fairseq 0.10.1 training won't work for the moment.

it seems not working for now.

**Comment by mzeidhassan** [comment]
@LoekvanKooten , just for your information, @davidecaroselli released a new MMT version (v4.9.5) a week ago with this new feature:

"Added support for CUDA 11 and Fairseq 0.10."

I thought I should let you know.

**Comment by LoekvanKooten** [comment]
Yes, thank you, I noticed! However, at this moment it doesn't seem to give any added value due to speed issues. It does make ModernMT more future-proof though, which is a good thing.

**Comment by LoekvanKooten** [comment]
>     * before running `pip3 install -r requirements_cuda-11.txt` run `pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html` otherwise error occurs

Doesn't work. This still gives:
`Could not find a version that satisfies the requirement torch==1.7.1+cu110 (from -r requirements_cuda-11.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0)
No matching distribution found for torch==1.7.1+cu110 (from -r requirements_cuda-11.txt (line 6))
`

**Comment by davidecaroselli** [comment]
Hi Loek,

I believe pytorch has updated the package to `torch==1.7.1+cu111`, please try with that or, alternatively, you can force the installation of the old package with: `pip3 install torch==1.7.1+cu110 -f`.

**Comment by LoekvanKooten** [comment]
@davidecaroselli 

Solved! It is as @dagid4 said:

13. Edit ~/.local/lib/python3.8/site-packages/fairseq/utils.py change lines 441-444 from upper to lower:

`            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            else:`


`            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            module_parent, module_name = os.path.split(module_path)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            elif not os.path.exists(module_parent):`

That solves the error. Make sure you use consistent spaces and tabs as indents, and use the correct indents.

This confirms that the newest version of ModernMT can train on a 3090, provided you use Ubuntu 20.04. This is on fairsec 0.10.1. 0.10.2 isn't even needed, as long as you edit utils.py as shown above.

**Comment by LoekvanKooten** [comment]
What I can add already is that this training, slower as it may be (I didn't notice yet) seems to be much more stable. No crashes or anything. It just ploughs on and on. The constant crashes were a bit of a showstopper for me.

**Comment by LoekvanKooten** [comment]
Okay, so thanks to @dagid4, the full procedure is as follows:

1. Install Ubuntu 20.04 LTS (this does not work on 18.04)
2. Install NVIDIA driver
`sudo apt install nvidia-driver-455`
3. Install java
`sudo apt install -y openjdk-8-jdk`
4. Install development tools
`sudo apt install -y git maven cmake libboost-all-dev zlib1g-dev libbz2-dev`
5. Clone ModernMT
`git clone https://github.com/modernmt/modernmt.git modernmt && cd modernmt`
6. Delete requirements.txt and rename requirements_cuda-11.txt to requirements.txt.
7. Run installation script
`python3 setup.py`
8. Compile binaries
```
pushd src
mvn clean install
popd
9. Edit ~/.local/lib/python3.8/site-packages/fairseq/utils.py change lines 441-444 from upper to lower:

```
            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            else:
```
```
            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            module_parent, module_name = os.path.split(module_path)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            elif not os.path.exists(module_parent):
```

Use a Python editor or make very sure you use indents, spaces and tabs consistently, else Python will throw an error.

Happy training!

My first engine has been trained and is actually working.

**Comment by davidecaroselli** [comment]
Thank you @LoekvanKooten !
I will add your guidelines to the INSTALL.md document!

**Comment by EtienneAb3d** [comment]
Just to be sure, at the end of all this, is the 30XX series validated for both training and translating with ModernMT ?

**Comment by LoekvanKooten** [comment]
Yes, and perfectly stable now. Not one crash. Not during translation. Not during training. Not once.
