### ISSUE TITLE
Newest version of ModernMT still does absolutely nothing on a 3090

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#589]
[training.log](https://github.com/modernmt/modernmt/files/6205305/training.log)
Hi all,

There we go again. I'm getting really tired of this.

1. nvidia-smi tells me 455.23.05 is neatly installed. The 3090 is visible in slot 0.
2. CUDA 11.1 installed.
3. libcudnn8_8.1.1.33-1+cuda11.2_amd64.deb installed.

All looks good, right? ModernMT can start and it can serve. However, it cannot train. It sees the GPU and does not complain. However, once it starts training the neural network, *absolutely nothing* happens. training.log clearly fires up the network, and then nothing. No error, nothing. The tensorboard.log directory stays empty. 

The silence is deafening. What is going on. Why doesn't this work?

**Comment by LoekvanKooten** [comment]
After a while, I got:

`ERROR Unexpected exception: Command 'fairseq-train /home/loek/modernmt/runtime/procdut/tmp/training/data_generated --save-dir /home/loek/modernmt/runtime/procdut/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt/build/mmt-4.9.5.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas (0.9, 0.98) --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10' failed with exit code 1`

Inputting the same without the --adam-betas (which gives a syntax error), gives:

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [27, 112, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

**Comment by davidecaroselli** [comment]
Hi Loek,

as stated in the announcing post here https://github.com/modernmt/modernmt/issues/574#issuecomment-748209465 training on 3090 is not supported due to a problem in fairseq.
By the way, I just double-checked and it seems that they have released a new version [fairseq 0.10.2](https://github.com/pytorch/fairseq/releases/tag/v0.10.2), but unfortunately we didn't have the chance to test it yet.

**Comment by LoekvanKooten** [comment]
I'm afraid that cu111 doesn't work either:
` Could not find a version that satisfies the requirement torch==1.7.1+cu111 (from -r /home/loek/modernmt/requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0)
No matching distribution found for torch==1.7.1+cu111 (from -r /home/loek/modernmt/requirements.txt (line 6))`

Just 1.7.1 installs, but I'm not sure whether that is enough.

Trying now with 1.7.1 and 0.10.2

**Comment by LoekvanKooten** [comment]
And that gives:

`loek@DORAEMON:~/modernmt$ ./mmt create zh nl data/procdut -e procdut
Traceback (most recent call last):
  File "./mmt", line 80, in <module>
    main()
  File "./mmt", line 28, in main
    from cli import cleaning, datagen, train, create, server, translate, evaluate, memory
  File "/home/loek/modernmt/cli/datagen.py", line 14, in <module>
    from mmt.textencoder import SubwordDictionary
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/loek/modernmt/build/mmt-4.9.5.jar/mmt/__init__.py", line 4, in <module>
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/__init__.py", line 19, in <module>
    import fairseq.criterions  # noqa
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/criterions/__init__.py", line 38, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/criterions/masked_lm.py", line 15, in <module>
    class MaskedLmLoss(FairseqCriterion):
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/registry.py", line 65, in register_x_cls
    registry_name, cls.__name__
ValueError: Cannot register criterion with duplicate class name (MaskedLmLoss)`

I'm stuck again.

**Comment by LoekvanKooten** [comment]
Brand-new install on Ubuntu 20.04.

`ERROR Unexpected exception: Command 'fairseq-preprocess --source-lang sl --target-lang tl --user-dir /home/loek/modernmt/build/mmt-4.9.5.jar/mmt --task mmt_translation --trainpref /home/loek/modernmt/runtime/procdut/tmp/training/_temp_datagen/encoded_corpora/train --validpref /home/loek/modernmt/runtime/procdut/tmp/training/_temp_datagen/encoded_corpora/dev --destdir /home/loek/modernmt/runtime/procdut/tmp/training/data_generated --workers 8 --srcdict /home/loek/modernmt/runtime/procdut/tmp/training/data_generated/model.vcb --joined-dictionary --dataset-impl mmap' failed with exit code 1`

Inputting this command gives: 

`ERROR Unexpected exception: Command 'fairseq-preprocess --source-lang sl --target-lang tl --user-dir /home/loek/modernmt/build/mmt-4.9.5.jar/mmt --task mmt_translation --trainpref /home/loek/modernmt/runtime/procdut/tmp/training/_temp_datagen/encoded_corpora/train --validpref /home/loek/modernmt/runtime/procdut/tmp/training/_temp_datagen/encoded_corpora/dev --destdir /home/loek/modernmt/runtime/procdut/tmp/training/data_generated --workers 8 --srcdict /home/loek/modernmt/runtime/procdut/tmp/training/data_generated/model.vcb --joined-dictionary --dataset-impl mmap' failed with exit code 1`

**Comment by LoekvanKooten** [comment]
mmt-4.9.5.jar is there. I can't look inside it. Build showed no errors.

**Comment by LoekvanKooten** [comment]
Translation is working, by the way, even though on the first try, for some reason...

python3 setup.py

did NOT install Cassandra and Kafka (they were not there in the vendor directory). So that leaves the above error about the jar file.

**Comment by LoekvanKooten** [comment]
Solved. See solution in https://github.com/modernmt/modernmt/issues/574#issuecomment-748209465

**Comment by CSNPVG** [comment]
Hi Loek,
Translation can't work
And that gives:
2022-06-04 13:27:29 | INFO | CreateActivity | Training started: engine=default, lang_pair=en__it

=========== TRAINING STARTED ===========

ENGINE:   default
LANGUAGE: en > it

(1/4) Cleaning corpora
2022-06-04 13:27:29 | INFO | CreateActivity | Training step "clean" started
    (1/6) Cleaning corpora...                                    2022-06-04 13:27:29 | INFO | CleaningActivity | Training step "clean" started
2022-06-04 13:27:30 | INFO | CleaningActivity | Training step "clean" completed in 1s
DONE in 1s
    (2/6) De-duplicate corpora...                                2022-06-04 13:27:30 | INFO | CleaningActivity | Training step "dedup" started
2022-06-04 13:27:31 | INFO | CleaningActivity | Training step "dedup" completed in 0s
DONE in 0s
    (3/6) Preprocess corpora...                                  2022-06-04 13:27:31 | INFO | CleaningActivity | Training step "preprocess" started
2022-06-04 13:27:32 | INFO | CleaningActivity | Training step "preprocess" completed in 0s
DONE in 0s
    (4/6) Creating aligner filter...                             2022-06-04 13:27:32 | INFO | CleaningActivity | Training step "make_filter" started
2022-06-04 13:27:33 | INFO | CleaningActivity | Training step "make_filter" completed in 0s
DONE in 0s
    (5/6) Scoring corpora...                                     2022-06-04 13:27:33 | INFO | CleaningActivity | Training step "score" started
2022-06-04 13:27:33 | INFO | CleaningActivity | Training step "score" completed in 0s
DONE in 0s
    (6/6) Apply aligner-based filter...                          2022-06-04 13:27:33 | INFO | CleaningActivity | Training step "apply_filter" started
2022-06-04 13:27:33 | INFO | CleaningActivity | Applying aligner filter with: good_avg = -5.090020, good_std_dev = 1.840280, bad_avg = -11.372900, bad_std_dev = 3.509210
2022-06-04 13:27:33 | INFO | CleaningActivity | Training step "apply_filter" completed in 0s
DONE in 0s
2022-06-04 13:27:33 | INFO | CreateActivity | Training step "clean" completed in 3s
(1/4) Cleaning corpora DONE in 3s
(2/4) Creating engine
2022-06-04 13:27:33 | INFO | CreateActivity | Training step "mkengine" started
2022-06-04 13:27:33 | INFO | CreateActivity | Training step "mkengine" completed in 0s
(2/4) Creating engine DONE in 0s
(3/4) Generating binary archives
2022-06-04 13:27:33 | INFO | CreateActivity | Training step "datagen" started
    (1/4) Tokenize corpora...                                    2022-06-04 13:27:33 | INFO | DatagenActivity | Training step "tokenize" started
2022-06-04 13:27:34 | INFO | DatagenActivity | Training step "tokenize" completed in 1s
DONE in 1s
    (2/4) Training BPE model...                                  2022-06-04 13:27:34 | INFO | DatagenActivity | Training step "bpe_create" started
2022-06-04 13:27:34 | INFO | SubwordDictionary::Factory | Collecting counts BEGIN
2022-06-04 13:27:34 | INFO | SubwordDictionary::Factory | Collecting counts END
2022-06-04 13:27:34 | INFO | SubwordDictionary::Factory | Vocabulary max_size attempt with candidates = [16000, 32000]
2022-06-04 13:27:34 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:34 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:34 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 122
2022-06-04 13:27:34 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:34 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 119
2022-06-04 13:27:34 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:34 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 122
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 119
2022-06-04 13:27:35 | INFO | SubwordDictionary::Factory | Generating vocab file: min = 1, max = 16000
2022-06-04 13:27:35 | INFO | SubwordDictionary::Factory | Trying min_count 8000
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 156
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 144
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 150
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 147
2022-06-04 13:27:35 | INFO | SubwordDictionary::Factory | Trying min_count 4000
2022-06-04 13:27:35 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 198
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 176
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 181
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 180
2022-06-04 13:27:36 | INFO | SubwordDictionary::Factory | Trying min_count 2000
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 287
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 215
2022-06-04 13:27:36 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 229
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 226
2022-06-04 13:27:37 | INFO | SubwordDictionary::Factory | Trying min_count 1000
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 465
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 308
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 327
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 318
2022-06-04 13:27:37 | INFO | SubwordDictionary::Factory | Trying min_count 500
2022-06-04 13:27:37 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 807
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 442
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 465
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 461
2022-06-04 13:27:38 | INFO | SubwordDictionary::Factory | Trying min_count 250
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 1377
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 679
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 726
2022-06-04 13:27:38 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 727
2022-06-04 13:27:39 | INFO | SubwordDictionary::Factory | Trying min_count 125
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 2437
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 1074
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 1136
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 1123
2022-06-04 13:27:39 | INFO | SubwordDictionary::Factory | Trying min_count 62
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 4187
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 1664
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 1783
2022-06-04 13:27:39 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 1763
2022-06-04 13:27:40 | INFO | SubwordDictionary::Factory | Trying min_count 31
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 6887
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 2642
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 2767
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 2742
2022-06-04 13:27:40 | INFO | SubwordDictionary::Factory | Trying min_count 15
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 11235
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 4078
2022-06-04 13:27:40 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 4247
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 4203
2022-06-04 13:27:41 | INFO | SubwordDictionary::Factory | Trying min_count 7
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 17999
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 6232
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 6464
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 6405
2022-06-04 13:27:41 | INFO | SubwordDictionary::Factory | Trying min_count 3
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 28450
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 9578
2022-06-04 13:27:41 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 9844
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 9791
2022-06-04 13:27:42 | INFO | SubwordDictionary::Factory | Trying min_count 1
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 BEGIN
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 1 END, vocab_size = 44841
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 BEGIN
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 2 END, vocab_size = 13349
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 BEGIN
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 3 END, vocab_size = 13349
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 BEGIN
2022-06-04 13:27:42 | INFO | SubwordDictionary::build_from_token_counts | iteration 4 END, vocab_size = 13349
2022-06-04 13:27:42 | INFO | DatagenActivity | Training step "bpe_create" completed in 8s
DONE in 8s
    (3/4) Encoding training corpora...                           2022-06-04 13:27:42 | INFO | DatagenActivity | Training step "bpe_encode" started

ERROR Unexpected exception: <lambda>() takes 1 positional argument but 2 were given
