### ISSUE TITLE
How to run ModernMT on a 30xx: updated on 12 august 2022

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#620]
1. Install Ubuntu 20.04 LTS (this does not work on 18.04)
2. Install NVIDIA driver
`sudo apt install nvidia-driver-455`
(I don't believe higher drivers like 460 will work.) There's a possibility this doesn't work. In that case, you need to manually download the driver from NVIDIA's website and install it from there. Make sure you have deleted all NVIDIA drivers, CUDA files and cuDNN files from your system first. Do a complete purge (just make sure the nouveau driver stays alive). Or better: start from a clean system if you want to make absolutely sure.
3. Install java
`sudo apt install -y openjdk-8-jdk`
4. Install development tools
`sudo apt install -y git maven cmake libboost-all-dev zlib1g-dev libbz2-dev`
5. Clone ModernMT
`git clone https://github.com/modernmt/modernmt.git modernmt && cd modernmt`
6. Delete requirements.txt and rename requirements_cuda-11.txt to requirements.txt. This is what it should look like:
```
regex
sacrebleu==1.4.14
requests
cachetools
tensorboardX==2.1
torch==1.7.0+cu110
fairseq==0.10.1
protobuf==3.20.*
```
(No, cu111 does not work. Torch 1.7.1 no longer works either.)
7. Debug ModernMT. In ChineseCharacterConverter.java, deep in one of ModernMT's directories, line 44...

            if (iterator != null)
                iterator.close();

...should read...

            if (iterator != null)
                try {
                iterator.close();
                } catch (IOException e) {
                  throw new Error(e);
                }
Use a Java editor or make very sure you use indents, spaces and tabs consistently, else Java will throw an error.
8. Instal Python 3.8
`sudo apt install python3.8`
9. Update installation script. Line 11 should read:
CASSANDRA_VERSION = '3.11.13'
10. Update pom.xml in /src as follows
`<cassandra.version>3.11.13</cassandra.version>`
and
```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
        </dependency>
```
12. Run installation script
`python3 setup.py`
13. Compile binaries
```
pushd src
mvn clean install
popd

```
14. Edit ~/.local/lib/python3.8/site-packages/fairseq/utils.py change lines 441-444 from upper to lower:

```
            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            else:
```

```
            fairseq_rel_path = os.path.join(os.path.dirname(__file__), args.user_dir)
            module_parent, module_name = os.path.split(module_path)
            if os.path.exists(fairseq_rel_path):
                module_path = fairseq_rel_path
            elif not os.path.exists(module_parent):
```

Use a Python editor or make very sure you use indents, spaces and tabs consistently, else Python will throw an error.

If you get strange errors the first time, try a reboot and double-check the modernmt/vendor directory to see if Kafka and Cassandra have actually been installed there.

**Comment by LoekvanKooten** [comment]
@nicolabertoldi You probably want to look into this!

**Comment by LoekvanKooten** [comment]
Stuck now. The engines start, but respond as follows:

```
<h2>HTTP ERROR 500 java.lang.IncompatibleClassChangeError: Found 
interface org.eclipse.jetty.http.pathmap.PathSpec, but class was 
expected</h2>


URI: | /translate
-- | --
500
java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.http.pathmap.PathSpec, but class was expected
-
java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.http.pathmap.PathSpec, but class was expected


<h3>Caused by:</h3><pre>java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.http.pathmap.PathSpec, but class was expected
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:460)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at eu.modernmt.api.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.lang.Thread.run(Thread.java:750)
</pre>
```

**Comment by mzeidhassan** [comment]
Hi @nicolabertoldi and @davidecaroselli ,

Hope all is well with you and your loved ones.

Do you plan guys to share the latest open-source release of MMT which is based on MarianMT as Nicola mentioned in Nvidia's session last year? Or should we all consider open-source MMT a dead and abandoned project for good? 

Thanks

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan , I'm sorry but there are no plans to port new features to the open-source in the near feature, including the port of the new ModernMT version.

The current open-source code will remain available together with all current and previous versions of Docker images available here: https://hub.docker.com/r/modernmt/master.

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli for letting us know.

**Comment by mzeidhassan** [comment]
Hi @LoekvanKooten 
have you managed to fix this error?

`HTTP ERROR 500 java.lang.IncompatibleClassChangeError: `

Thanks

**Comment by LoekvanKooten** [comment]
@mzeidhassan As this version of ModernMT is now abandonware, I moved on to ModernMT online. To maintain control about my translation memories, I developed my won CAT tool which can be found here: https://www.c4ttitude.com/

**Comment by mzeidhassan** [comment]
Thanks @LoekvanKooten ! I thought you found a solution to that error. Good luck with your new tool.
